### ISSUE TITLE
Download won't start for a magnet while it starts fine using another clients

### ISSUE THREAD

**Issue by entr** [scakemyer/plugin.video.quasar#342]
```log
00:23:47 T:140476518217472  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/play?uri=magnet%3A%3Fxt%3Durn%3Abtih%3A3da22d3e3d6f360621abfefd53b4d2e83c94a2b7%26dn%3DSuits.S03.720p.HDTV.x264 from ['plugin://plugin.video.quasar/play', '24', '?uri=magnet%3A%3Fxt%3Durn%3Abtih%3A3da22d3e3d6f360621abfefd53b4d2e83c94a2b7%26dn%3DSuits.S03.720p.HDTV.x264']
00:23:47 T:140478414567168  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ addTorrent       Adding torrent
00:23:47 T:140478414567168  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ addTorrent       Setting save path to /mnt/a4ef42e6-56be-430b-8e58-dbb0e4215739/Popcorn-Time
00:23:47 T:140478414567168  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ addTorrent       Checking for fast resume data in 3da22d3e3d6f360621abfefd53b4d2e83c94a2b7.fastresume
00:23:47 T:140478414567168  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ addTorrent       Enabling sequential download
00:23:47 T:140478414567168  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ addTorrent       Downloading Suits.S03.720p.HDTV.x264
00:23:47 T:140478414567168  NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        torrent_added_alert: Suits.S03.720p.HDTV.x264 added
00:23:47 T:140478414567168  NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        state_changed_alert: Suits.S03.720p.HDTV.x264: state changed to: dl metadata
00:23:47 T:140478414567168  NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        add_torrent_alert: added torrent: magnet:?xt=urn:btih:3da22d3e3d6f360621abfefd53b4d2e83c94a2b7&dn=Suits.S03.720p.HDTV.x264&as=http%3A%2F%2Ftorcache.net%2Ftorrent%2F3da22d3e3d6f360621abfefd53b4d2e83c94a2b7.torrent&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fexodus.desync.com%3A6969&tr=udp%3A%2F%2Ftracker.pomf.se&tr=udp%3A%2F%2Ftracker.blackunicorn.xyz%3A6969&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Fpow7.com%3A80%2Fannounce
00:23:47 T:140478414567168  NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        torrent_resumed_alert: Suits.S03.720p.HDTV.x264 resumed
00:23:47 T:140478414567168  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ playerLoop       Buffer loop
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar] Traceback (most recent call last):
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]   File "/home/zlatev/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 112, in run
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]     data = _json(url)
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]   File "/home/zlatev/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 48, in _json
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]     return _opener.open(url, data, timeout)
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 404, in open
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]     response = self._open(req, data)
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 422, in _open
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]     '_open', req)
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]     result = func(*args)
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]     return self.do_open(httplib.HTTPConnection, req)
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]     r = h.getresponse(buffering=True)
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]     response.begin()
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/httplib.py", line 415, in begin
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]     version, status, reason = self._read_status()
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]     line = self.fp.readline(_MAXLINE + 1)
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/socket.py", line 476, in readline
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]     data = self._sock.recv(self._rbufsize)
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar] timeout: timed out
00:28:47 T:140476518217472   ERROR: [plugin.video.quasar]
00:28:47 T:140479093368576  NOTICE: PulseAudio: Opened device alsa_output.pci-0000_00_1b.0.analog-stereo in pcm mode with Buffersize 150 ms
00:28:47 T:140479496517632   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.quasar/play?uri=magnet%3A%3Fxt%3Durn%3Abtih%3A3da22d3e3d6f360621abfefd53b4d2e83c94a2b7%26dn%3DSuits.S03.720p.HDTV.x264]
```

This is linux kodi but I experience the same on my odroid c1.
Not using proxy. Any clue?

**Comment by scakemyer** [comment]
From those logs, the download clearly starts, so it's probably just your buffer that's too small and can't be played. Other than that, I can't help with specific torrents, sorry.

**Comment by entr** [comment]
@scakemyer increasing the buffer to 100(default 20) allowed quasar to get pass the "finding..." modal and allow me to choose which file to play (since it's a whole season). Can you elaborate a bit on how exactly buffer size affects the magnet resolving and why that might be an issue at all? Thanks.

**Comment by entr** [comment]
OK, I'm pretty confident there's something quite wrong (at least for me). I continue to find magnets that would download (download fast, in fact) in any desktop client but quasar won't. It doesn't make sense to me how small buffer could be a problem in the first place. Is 100MB considered small? Any help appreciated!

**Comment by nickolayrusev** [comment]
man i had a similar problem, i reported it here. https://github.com/scakemyer/plugin.video.quasar/issues/243

do you have "download path" set?
I noticed that do not happen every time, I don't know where is the problem but sometimes fails to start download, if I try with other torrent clients starts immediately...

**Comment by entr** [comment]
Yes, my "download path" is correctly set to a pluggable USB drive which now reminds me to test setting "download path" onto the sdcard and test again problematic magnets. What I noticed is that well seeded torrents (like >40 seeds) will start buffering just fine within a couple of seconds while worse seeded ones won't. That would be perfectly fine to live with unless other clients manage to do the job effortlessly.

**Comment by entr** [comment]
For everyone experiencing similar issues. Clearing cache seems to fix my problem. Sadly I wasn't able to figure out why exactly cache clear is required but it is a quick workaround I could go with for now. Just open context menu > Add-on Settings > OK (save clears the cache) or Advanced > Clear cache.
