### ISSUE TITLE
Quasar iPad - trouble launching addon

### ISSUE THREAD

**Issue by QuasarKodi** [scakemyer/plugin.video.quasar#348]
[Quasar iPad.zip](https://github.com/scakemyer/plugin.video.quasar/files/160069/Quasar.iPad.zip)
Hi all,

I've installed Kodi on my iPad, but unfortunately the Quasar addon doesn't seem to launch. I've attached the kodi.log and a screenshot of the issue to help troubleshoot.
I don't really understand the log but it seems the addon can't find it's path.
In case I can be of any help, to hesitate to write here.

Sent from iPad

**Comment by QuasarKodi** [comment]
> 09:17:14 T:1076703232  NOTICE: special://profile/ is mapped to: special://masterprofile/
09:17:14 T:1076703232  NOTICE: -----------------------------------------------------------------------
09:17:14 T:1076703232  NOTICE: Starting Kodi (16.0 Git:2016-02-20-a5f3a99). Platform: iOS ARM (Thumb) 32-bit
09:17:14 T:1076703232  NOTICE: Using Release Kodi x32 build
09:17:14 T:1076703232  NOTICE: Kodi compiled Feb 20 2016 by Clang 6.0 (clang-600.0.56) for iOS ARM (Thumb) 32-bit version 5.1.0 (50100)
09:17:14 T:1076703232  NOTICE: Running on Apple Inc. iPad4,4 with iOS 9.0.2, kernel: Darwin ARM 64-bit version 15.0.0
09:17:14 T:1076703232  NOTICE: Host CPU: arm64 v8, 2 cores available
09:17:14 T:1076703232  NOTICE: ARM Features: Neon enabled
09:17:14 T:1076703232  NOTICE: special://xbmc/ is mapped to: /private/var/db/stash/_.vYoSCE/Applications/Kodi.app/AppData/AppHome
09:17:14 T:1076703232  NOTICE: special://xbmcbin/ is mapped to: /private/var/db/stash/_.vYoSCE/Applications/Kodi.app/AppData/AppHome
09:17:14 T:1076703232  NOTICE: special://masterprofile/ is mapped to: /var/mobile/Library/Preferences/Kodi/userdata
09:17:14 T:1076703232  NOTICE: special://home/ is mapped to: /var/mobile/Library/Preferences/Kodi
09:17:14 T:1076703232  NOTICE: special://temp/ is mapped to: /var/mobile/Library/Preferences/Kodi/temp
09:17:14 T:1076703232  NOTICE: special://frameworks/ is mapped to: /Applications/Kodi.app/Frameworks
09:17:14 T:1076703232  NOTICE: The executable running is: /Applications/Kodi.app/Kodi
09:17:14 T:1076703232  NOTICE: Local hostname: Nikos-iPad
09:17:14 T:1076703232  NOTICE: Log File is located: /var/mobile/Library/Preferences/kodi.log
09:17:14 T:1076703232  NOTICE: -----------------------------------------------------------------------
09:17:14 T:1076703232  NOTICE: load settings...

**Quasar relevant information below**

> 09:17:16 T:1081290752   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (10, 'No child processes')
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.quasar/service.py", line 4, in <module>
                                                from quasar import service
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.quasar/resources/site-packages/quasar/service.py", line 4, in <module>
                                                from quasar.rpc import server_thread
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.quasar/resources/site-packages/quasar/rpc.py", line 13, in <module>
                                                from quasar.osarch import PLATFORM
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.quasar/resources/site-packages/quasar/osarch.py", line 41, in <module>
                                                PLATFORM = get_platform()
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.quasar/resources/site-packages/quasar/osarch.py", line 9, in get_platform
                                                "version": platform.release()
                                              File "/Users/Shared/jenkins/workspace/IOS/tools/depends/xbmc-depends/iphoneos8.1_armv7-target/lib/python2.6/platform.py", line 1232, in release
                                              File "/Users/Shared/jenkins/workspace/IOS/tools/depends/xbmc-depends/iphoneos8.1_armv7-target/lib/python2.6/platform.py", line 1180, in uname
                                              File "/Users/Shared/jenkins/workspace/IOS/tools/depends/xbmc-depends/iphoneos8.1_armv7-target/lib/python2.6/platform.py", line 937, in _syscmd_uname
                                            IOError: (10, 'No child processes')
                                            -->End of Python script error report<--
09:17:20 T:1080143872 WARNING: DARWINIOS: underflow (0 vs 8192 bytes)

**Comment by johnnyslt** [comment]
Did you uninstall Pulsar first?

**Comment by scakemyer** [comment]
iOS was never on the supported platform list, and from those logs I'm not tempted to try to add it. But thanks for the report, it's useful information in case someone wants to look into it.
