### ISSUE TITLE
When adding any series to the Kodi favorites, every few seconds HTTPError appears

### ISSUE THREAD

**Issue by konst1988** [scakemyer/plugin.video.quasar#378]
If i add a series from quasar to Kodi's favorites,  (right click and select add to favorites), an error is appeared every few seconds.
It does not matter what series i select.
From log:
```
17:08:24 T:7660  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/show/1399/seasons&widget=true from ['plugin://plugin.video.quasar/show/1399/seasons&widget=true', '133', '']
17:08:24 T:6080  NOTICE: [plugin.video.quasar] [GIN] 2016/03/12 - 17:08:24 |[97;43m 404 [0m|             0 | ::1 |[97;44m  [0m GET     /show/1399/seasons&widget=true
17:08:24 T:7660   ERROR: [plugin.video.quasar] Traceback (most recent call last):
17:08:24 T:7660   ERROR: [plugin.video.quasar]   File "C:\Users\konst\AppData\Roaming\Kodi\addons\plugin.video.quasar\resources\site-packages\quasar\navigation.py", line 112, in run
17:08:24 T:7660   ERROR: [plugin.video.quasar]     data = _json(url)
17:08:24 T:7660   ERROR: [plugin.video.quasar]   File "C:\Users\konst\AppData\Roaming\Kodi\addons\plugin.video.quasar\resources\site-packages\quasar\navigation.py", line 48, in _json
17:08:24 T:7660   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
17:08:24 T:7660   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
17:08:24 T:7660   ERROR: [plugin.video.quasar]     return _opener.open(url, data, timeout)
17:08:24 T:7660   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 410, in open
17:08:24 T:7660   ERROR: [plugin.video.quasar]     response = meth(req, response)
17:08:24 T:7660   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 523, in http_response
17:08:24 T:7660   ERROR: [plugin.video.quasar]     'http', request, response, code, msg, hdrs)
17:08:24 T:7660   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 448, in error
17:08:24 T:7660   ERROR: [plugin.video.quasar]     return self._call_chain(*args)
17:08:24 T:7660   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
17:08:24 T:7660   ERROR: [plugin.video.quasar]     result = func(*args)
17:08:24 T:7660   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 531, in http_error_default
17:08:24 T:7660   ERROR: [plugin.video.quasar]     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
17:08:24 T:7660   ERROR: [plugin.video.quasar] HTTPError: HTTP Error 404: Not Found
17:08:24 T:7660   ERROR: [plugin.video.quasar]
17:08:24 T:1472   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.quasar/show/1399/seasons&widget=true
```

**Comment by lordjg** [comment]
same for me

**Comment by michalwski** [comment]
I had the same problem. I managed to solve it by clearing quasar's cache. You can find this in the plugin settings on `advanced` tab.
