### ISSUE TITLE
0.9.30 - Trakt 500 error

### ISSUE THREAD

**Issue by sagarun** [scakemyer/plugin.video.quasar#394]
When i tried to activate trakt i get this

```
18:23:16 557.054199 T:1461162992   ERROR: [plugin.video.quasar] Traceback (most recent call last):
18:23:16 557.056824 T:1461162992   ERROR: [plugin.video.quasar]   File "/home/osmc/.kodi/addons/plugin.video.quasar/resources/site-pack
ages/quasar/navigation.py", line 112, in run
18:23:16 557.059692 T:1461162992   ERROR: [plugin.video.quasar]     data = _json(url)
18:23:16 557.062378 T:1461162992   ERROR: [plugin.video.quasar]   File "/home/osmc/.kodi/addons/plugin.video.quasar/resources/site-pack
ages/quasar/navigation.py", line 48, in _json
18:23:16 557.064880 T:1461162992   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
18:23:16 557.067139 T:1461162992   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
18:23:16 557.069397 T:1461162992   ERROR: [plugin.video.quasar]     return opener.open(url, data, timeout)
18:23:16 557.071472 T:1461162992   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 437, in open
18:23:16 557.073669 T:1461162992   ERROR: [plugin.video.quasar]     response = meth(req, response)
18:23:16 557.076294 T:1461162992   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
18:23:16 557.078674 T:1461162992   ERROR: [plugin.video.quasar]     'http', request, response, code, msg, hdrs)
18:23:16 557.081116 T:1461162992   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 475, in error
18:23:16 557.082153 T:1461162992   ERROR: [plugin.video.quasar]     return self._call_chain(*args)
18:23:16 557.083191 T:1461162992   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
18:23:16 557.084473 T:1461162992   ERROR: [plugin.video.quasar]     result = func(*args)
18:23:16 557.085571 T:1461162992   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_defaul$
18:23:16 557.086670 T:1461162992   ERROR: [plugin.video.quasar]     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
18:23:16 557.087769 T:1461162992   ERROR: [plugin.video.quasar] HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by scakemyer** [comment]
Fixed, that one was a rookie mistake... It didn't prevent authentication though.
