### ISSUE TITLE
Daemon doesn't start, Error 22 Invalid Argument

### ISSUE THREAD

**Issue by rustytrawler** [scakemyer/plugin.video.quasar#412]
OpenElec 5.0.8
Kodi 14.2
Quasar 0.9.32

Quasar daemon doesn't start anymore. It was working until a few days ago. I guess it got updated and stopped working then.

Here's the relevant log:

```
11:01:57 T:1717564480   ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
11:01:57 T:1717564480   ERROR: CCurlFile::CReadState::Connect, didn't get any data from stream.
11:01:57 T:1717564480   ERROR: Open - failed to open source <http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml.md5>
11:01:57 T:1717564480   ERROR: Failed to fetch checksum for directory listing http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml for repository repository.quasar.
11:02:05 T:1576043584  NOTICE: [plugin.video.quasar] quasard: starting quasard
11:02:10 T:1567654976  NOTICE: [plugin.video.quasar] quasar: starting jsonrpc service
11:02:11 T:1755759680  NOTICE: -->Python Interpreter Initialized<--
11:02:12 T:1806836800  NOTICE: Previous line repeats 2 times.
11:02:12 T:1806836800  NOTICE: script.grab.fanart: Grab Fanart Service Started
11:02:13 T:1755759680  NOTICE: ## OpenELEC Addon ## 0.5.8
11:02:14 T:1657791552  NOTICE: Thread LanguageInvoker start, auto delete: false
11:02:17 T:1745876032  NOTICE:  StorageServer Module loaded RUN
11:02:17 T:1576043584   ERROR: [plugin.video.quasar] Traceback (most recent call last):
11:02:17 T:1576043584   ERROR: [plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 141, in quasard_thread
11:02:17 T:1576043584   ERROR: [plugin.video.quasar]     proc = start_quasard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
11:02:17 T:1576043584   ERROR: [plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 101, in start_quasard
11:02:17 T:1576043584   ERROR: [plugin.video.quasar]     quasar_dir, quasar_binary = get_quasar_binary()
11:02:17 T:1576043584   ERROR: [plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 63, in get_quasar_binary
11:02:17 T:1576043584   ERROR: [plugin.video.quasar]     if not os.path.exists(dest_binary_path) or get_quasard_checksum(dest_binary_path) != get_quasard_checksum(binary_path):
11:02:17 T:1576043584   ERROR: [plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 30, in get_quasard_checksum
11:02:17 T:1576043584   ERROR: [plugin.video.quasar]     fp.seek(-40, os.SEEK_END)  # we put a sha1 there
11:02:17 T:1576043584   ERROR: [plugin.video.quasar] IOError: [Errno 22] Invalid argument
11:02:17 T:1576043584   ERROR: [plugin.video.quasar]
11:02:17 T:1745876032  NOTICE: StorageClient-2.5.4 Starting server
11:02:17 T:1576043584   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/threading.py", line 504, in run
                                              File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 141, in quasard_thread
                                                proc = start_quasard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 101, in start_quasard
                                                quasar_dir, quasar_binary = get_quasar_binary()
                                              File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 63, in get_quasar_binary
                                                if not os.path.exists(dest_binary_path) or get_quasard_checksum(dest_binary_path) != get_quasard_checksum(binary_path):
                                              File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 30, in get_quasard_checksum
                                                fp.seek(-40, os.SEEK_END)  # we put a sha1 there
                                            IOError: [Errno 22] Invalid argument
```

**Comment by scakemyer** [comment]
Your binary is either corrupted or empty, just upgrade manually from the releases page.

**Comment by rustytrawler** [comment]
Nope. Just did that and resulted in the same error.

I have the arm7 binary. Isn't that the correct one? I'm using the Raspberry Pi 2.

**Comment by scakemyer** [comment]
That should be it, yes. There's just not much else I can tell from these logs. It wouldn't be a bad idea to upgrade your system either.

**Comment by rustytrawler** [comment]
I can do that. Let me get back to you on that.

**Comment by rustytrawler** [comment]
Just updated to Openelec 6.0.3, Kodi 15.2. I get exactly the same error as before. I have no Quasar Program Add-ons installed. How can I clear all Quasar's state?

**Comment by rustytrawler** [comment]
Ok. I got it to work only after deleting all quasar user data: `/storage/.kodi/userdata/addon_data/plugin.video.quasar`. After that I reinstalled and it started to work.

There is definitely a bug on your part here. Some addon data was causing this.

**Comment by scakemyer** [comment]
Because you had corrupted data in there doesn't mean there's a *bug on my part*. You probably caused this yourself by unplugging your Pi directly, then come here and blame me for your own mistakes. If you really think there's a bug causing this then find it yourself, it's all there.
