### ISSUE TITLE
plugin.video.quasar AttributeError: 'xbmcgui.ListItem' object has no attribute 'setArt'

### ISSUE THREAD

**Issue by Neobokero** [scakemyer/plugin.video.quasar#433]
No se inicia la reproducción del vídeo con el siguiente error.

video playback with the following error does not start.

```
  NOTICE: [plugin.video.quasar] [GIN] 2016/03/26 - 12:39:52 |[90;47m 302 [0m|   1m22.53125s | 127.0.0.1 |[97;44m  [0m GET     /play
   ERROR: [plugin.video.quasar] Traceback (most recent call last):
   ERROR: [plugin.video.quasar]   File "C:\Documents and Settings\Pc\Datos de programa\XBMC\addons\plugin.video.quasar\resources\site-packages\quasar\navigation.py", line 112, in run
   ERROR: [plugin.video.quasar]     data = _json(url)
   ERROR: [plugin.video.quasar]   File "C:\Documents and Settings\Pc\Datos de programa\XBMC\addons\plugin.video.quasar\resources\site-packages\quasar\navigation.py", line 83, in _json
   ERROR: [plugin.video.quasar]     item.setArt({
   ERROR: [plugin.video.quasar] AttributeError: 'xbmcgui.ListItem' object has no attribute 'setArt'
   ERROR: [plugin.video.quasar]
 WARNING: CWin32DirectSound::GetSpace - buffer underrun - W:10576, P:440, O:3528.
   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.quasar/play?uri=http***.torrent]
  NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        save_resume_data_alert: *** resume data generated
  NOTICE: [plugin.video.quasar] INFO  btservice    ▶ saveResumeDataConsumer  Saving resume data for *** to 528c83b1d90692a540ee81df42d0599176b3ad4c.fastresume
  NOTICE: [plugin.video.quasar] WARN  btplayer     ▶ playerLoop       Playback was unable to start after 20 seconds. Aborting...
  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ Close            Removing the torrent and deleting files...
  NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        torrent_removed_alert: *** removed
  NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        torrent_deleted_alert:  -  deleted
  NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        cache_flushed_alert:  -
```

**Comment by scakemyer** [comment]
Which version of Kodi?
