### ISSUE TITLE
Quasar crashes in fresh Kodi 15.2 on Ubuntu 14.04 

### ISSUE THREAD

**Issue by Filosofos** [scakemyer/plugin.video.quasar#45]
Quasar 0.9.1 beta 2 crashes almost immediately in Linux and is the only add on installed.
Here is my log:
```
﻿00:48:02 T:3033204544  NOTICE: special://profile/ is mapped to: special://masterprofile/
00:48:02 T:3033204544  NOTICE: -----------------------------------------------------------------------
00:48:02 T:3033204544  NOTICE: Starting Kodi (15.2 Git:02e7013). Platform: Linux x86 32-bit
00:48:02 T:3033204544  NOTICE: Using Release Kodi x32 build
00:48:02 T:3033204544  NOTICE: Kodi compiled Oct 19 2015 by GCC 4.8.4 for Linux x86 32-bit version 3.13.11 (199947)
00:48:02 T:3033204544  NOTICE: Running on Ubuntu 14.04 LTS, kernel: Linux x86 32-bit version 3.13.0-24-generic
00:48:02 T:3033204544  NOTICE: FFmpeg statically linked, version: 2.6.4-kodi-2.6.4-Isengard
00:48:02 T:3033204544  NOTICE: Host CPU: Intel(R) Core(TM)2 Duo CPU P7450 @ 2.13GHz, 2 cores available
00:48:02 T:3033204544  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
00:48:02 T:3033204544  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/kodi
00:48:02 T:3033204544  NOTICE: special://masterprofile/ is mapped to: /home/filosofos/.kodi/userdata
00:48:02 T:3033204544  NOTICE: special://home/ is mapped to: /home/filosofos/.kodi
00:48:02 T:3033204544  NOTICE: special://temp/ is mapped to: /home/filosofos/.kodi/temp
00:48:02 T:3033204544  NOTICE: The executable running is: /usr/lib/kodi/kodi.bin
00:48:02 T:3033204544  NOTICE: Local hostname: Mikrosfilosofos
00:48:02 T:3033204544  NOTICE: Log File is located: /home/filosofos/.kodi/temp/kodi.log
00:48:02 T:3033204544  NOTICE: -----------------------------------------------------------------------
00:48:02 T:3033204544  NOTICE: load settings...
00:48:02 T:3033204544  NOTICE: Found 1 Lists of Devices
00:48:02 T:3033204544  NOTICE: Enumerated PULSE devices:
00:48:02 T:3033204544  NOTICE:     Device 1
00:48:02 T:3033204544  NOTICE:         m_deviceName      : Default
00:48:02 T:3033204544  NOTICE:         m_displayName     : Default
00:48:02 T:3033204544  NOTICE:         m_displayNameExtra: Default Output Device (PULSEAUDIO)
00:48:02 T:3033204544  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
00:48:02 T:3033204544  NOTICE:         m_channels        : FL,FR
00:48:02 T:3033204544  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
00:48:02 T:3033204544  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
00:48:02 T:3033204544  NOTICE:     Device 2
00:48:02 T:3033204544  NOTICE:         m_deviceName      : alsa_output.pci-0000_01_00.1.hdmi-stereo
00:48:02 T:3033204544  NOTICE:         m_displayName     : RV710/730 HDMI Audio [Radeon HD 4000 series] Digital Stereo (HDMI)
00:48:02 T:3033204544  NOTICE:         m_displayNameExtra: HDMI / DisplayPort (PULSEAUDIO)
00:48:02 T:3033204544  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
00:48:02 T:3033204544  NOTICE:         m_channels        : FL,FR
00:48:02 T:3033204544  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
00:48:02 T:3033204544  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
00:48:02 T:3033204544  NOTICE:     Device 3
00:48:02 T:3033204544  NOTICE:         m_deviceName      : alsa_output.pci-0000_00_1b.0.analog-stereo
00:48:02 T:3033204544  NOTICE:         m_displayName     : Εσωτερικός ήχος Analog Stereo
00:48:02 T:3033204544  NOTICE:         m_displayNameExtra: Ηχεία (PULSEAUDIO)
00:48:02 T:3033204544  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
00:48:02 T:3033204544  NOTICE:         m_channels        : FL,FR
00:48:02 T:3033204544  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
00:48:02 T:3033204544  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
00:48:02 T:3033204544  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
00:48:02 T:3033204544  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
00:48:02 T:3033204544  NOTICE: Default DVD Player: dvdplayer
00:48:02 T:3033204544  NOTICE: Default Video Player: dvdplayer
00:48:02 T:3033204544  NOTICE: Default Audio Player: paplayer
00:48:02 T:3033204544  NOTICE: Disabled debug logging due to GUI setting. Level 0.
00:48:02 T:3033204544  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
00:48:02 T:3033204544  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
00:48:02 T:3033204544  NOTICE: Loaded playercorefactory configuration
00:48:02 T:3033204544  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
00:48:02 T:3033204544  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
00:48:02 T:2965887808  NOTICE: Thread ActiveAE start, auto delete: false
00:48:02 T:3033000768  NOTICE: Thread AESink start, auto delete: false
00:48:02 T:3033000768  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
00:48:02 T:3033204544  NOTICE: Running database version Addons19
00:48:02 T:3033204544  NOTICE: ADDONS: Using repository repository.xbmc.org
00:48:02 T:3012557632  NOTICE: Thread RemoteControl start, auto delete: false
00:48:02 T:3033204544  NOTICE: Setup SDL
00:48:02 T:3033204544  NOTICE: Checking resolution 16
00:48:02 T:3033204544   ERROR: CWinSystemX11::XErrorHandler: BadAtom (invalid Atom parameter), type:0, serial:49, error_code:5, request_code:18 minor_code:0
00:48:02 T:3033204544  NOTICE: Using visual 0x1d7
00:48:02 T:3033204544  NOTICE: GL_VENDOR = X.Org
00:48:02 T:3033204544  NOTICE: GL_RENDERER = Gallium 0.4 on AMD RV710
00:48:02 T:3033204544  NOTICE: GL_VERSION = 3.0 Mesa 10.1.0
00:48:02 T:3033204544  NOTICE: GL_SHADING_LANGUAGE_VERSION = 1.30
00:48:02 T:3033204544  NOTICE: GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_texture_multisample GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_shader_bit_encoding GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_NV_vdpau_interop GL_ARB_base_instance GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_clear_buffer_object GL_ARB_invalidate_subdata GL_ARB_texture_storage_multisample GL_ARB_vertex_attrib_binding GL_KHR_debug GL_ARB_texture_mirror_clamp_to_edge GL_ARB_vertex_type_10f_11f_11f_rev
00:48:02 T:2870156096  NOTICE: Thread PeripBusCEC start, auto delete: false
00:48:02 T:2861763392  NOTICE: Thread PeripBusUSBUdev start, auto delete: false
00:48:02 T:3033204544  NOTICE: Running database version Addons19
00:48:02 T:3033204544  NOTICE: Running database version ViewModes6
00:48:02 T:3033204544  NOTICE: Running database version Textures13
00:48:02 T:3033204544  NOTICE: Running database version MyMusic52
00:48:02 T:3033204544  NOTICE: Running database version MyVideos93
00:48:02 T:3033204544  NOTICE: Running database version TV29
00:48:02 T:3033204544  NOTICE: Running database version Epg10
00:48:02 T:3033204544  NOTICE: start dvd mediatype detection
00:48:02 T:2957220672  NOTICE: Thread DetectDVDMedia start, auto delete: false
00:48:03 T:3033204544 WARNING: JSONRPC: Could not parse type "PVR.Details.Channel"
00:48:03 T:3033204544 WARNING: JSONRPC: Could not parse type "PVR.Details.ChannelGroup.Extended"
00:48:03 T:3033204544 WARNING: JSONRPC: Could not parse type "GUI.Property.Value"
00:48:03 T:3033204544 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
00:48:03 T:3033204544   ERROR: ExecuteAsync - Not executing non-existing script script.favourites
00:48:03 T:2820664128  NOTICE: Thread LanguageInvoker start, auto delete: false
00:48:03 T:2803878720  NOTICE: Previous line repeats 2 times.
00:48:03 T:2803878720  NOTICE: Thread JobWorker start, auto delete: true
00:48:03 T:3033204544  NOTICE: initialize done
00:48:03 T:3033204544  NOTICE: Running the application...
00:48:03 T:2778438464  NOTICE: Thread LanguageInvoker start, auto delete: false
00:48:03 T:2795223872  NOTICE: Previous line repeats 1 times.
00:48:03 T:2795223872  NOTICE: Thread JobWorker start, auto delete: true
00:48:03 T:3033204544  NOTICE: starting zeroconf publishing
00:48:03 T:3033204544  NOTICE: starting upnp client
00:48:03 T:2761653056  NOTICE: Thread JobWorker start, auto delete: true
00:48:03 T:3033204544  NOTICE: ES: Starting event server
00:48:03 T:2711034688  NOTICE: Thread TCPServer start, auto delete: false
00:48:03 T:2719427392  NOTICE: Thread EventServer start, auto delete: false
00:48:03 T:2719427392  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
00:48:03 T:2719427392  NOTICE: UDP: Listening on port 9777
00:48:03 T:2812271424  NOTICE: -->Python Interpreter Initialized<--
00:48:04 T:2700806976  NOTICE: Previous line repeats 3 times.
00:48:04 T:2700806976  NOTICE: Thread RSSReader start, auto delete: false
00:48:04 T:2786831168  NOTICE: -->Python Interpreter Initialized<--
00:48:04 T:2602548032  NOTICE: [plugin.video.quasar] quasar: starting jsonrpc service
00:48:04 T:2664401728  NOTICE: [plugin.video.quasar] quasard: starting quasard
00:48:04 T:2820664128  NOTICE: script.grab.fanart: Grab Fanart Service Started
00:48:04 T:2568977216  NOTICE: Thread FileCache start, auto delete: false
00:48:04 T:2664401728  NOTICE: [plugin.video.quasar] Deleting stale files set([])
00:48:05 T:2653944640  NOTICE: Thread FileCache start, auto delete: false
00:48:05 T:2602548032  NOTICE: u'POST / HTTP/1.1\r'
00:48:26 T:2829056832  NOTICE: Thread BackgroundLoader start, auto delete: false
00:48:27 T:2829056832  NOTICE: Thread LanguageInvoker start, auto delete: false
00:48:27 T:2829056832  NOTICE: -->Python Interpreter Initialized<--
00:48:27 T:3033204544   ERROR: GetDirectory - Error getting plugin://plugin.video.quasar/
00:48:27 T:3033204544   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/) failed
00:48:27 T:2829056832  NOTICE: Thread BackgroundLoader start, auto delete: false
00:48:42 T:2829056832  NOTICE: Thread LanguageInvoker start, auto delete: false
00:48:42 T:2829056832  NOTICE: -->Python Interpreter Initialized<--
00:48:50 T:3033204544  NOTICE: Storing total System Uptime
00:48:50 T:3033204544  NOTICE: Saving settings
00:48:50 T:3033204544  NOTICE: stop all
00:48:50 T:3033204544  NOTICE: stop player
00:48:50 T:3033204544  NOTICE: ES: Stopping event server
00:48:50 T:3033204544  NOTICE: stopping upnp
00:48:50 T:3033204544  NOTICE: stopping zeroconf publishing
00:48:50 T:2719427392  NOTICE: ES: UDP Event server stopped
00:48:50 T:3033204544  NOTICE: stop dvd detect media
00:48:50 T:3033204544  NOTICE: stop sap announcement listener
00:48:50 T:3033204544  NOTICE: clean cached files!
00:48:50 T:3033204544  NOTICE: unload skin
00:48:50 T:2812271424 WARNING: CPythonInvoker(2, /home/filosofos/.kodi/addons/service.library.data.provider/service.py): the python script "/home/filosofos/.kodi/addons/service.library.data.provider/service.py" has left several classes in memory that we couldn't clean up. The classes include: N14PythonBindings30XBMCAddon_xbmc_Player_DirectorE,N9XBMCAddon7xbmcgui6WindowE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE
00:48:51 T:2568977216  NOTICE: [plugin.video.quasar] quasard: exiting quasard daemon
00:48:51 T:2568977216   ERROR: Exception in thread Thread-4:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 763, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/filosofos/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 123, in wait_for_abortRequested
                                                proc.terminate()
                                              File "/usr/lib/python2.7/subprocess.py", line 1551, in terminate
                                                self.send_signal(signal.SIGTERM)
                                              File "/usr/lib/python2.7/subprocess.py", line 1546, in send_signal
                                                os.kill(self.pid, sig)
                                            OSError: [Errno 3] No such process
00:48:51 T:2778438464  NOTICE: [plugin.video.quasar] quasar: exiting quasard
00:48:51 T:2602548032  NOTICE: [plugin.video.quasar] quasar: exiting jsonrpc service
00:48:55 T:3033204544  NOTICE: stopped
00:48:55 T:3033204544  NOTICE: destroy
00:48:55 T:3033204544  NOTICE: closing down remote control service
00:48:55 T:3033204544  NOTICE: unload sections
00:48:55 T:3033204544  NOTICE: special://profile/ is mapped to: special://masterprofile/
00:48:55 T:3033204544  NOTICE: destroy
00:48:55 T:3033204544 WARNING: Attempted to remove window 10013 from the window manager when it didn't exist
00:48:55 T:3033204544 WARNING: Attempted to remove window 10014 from the window manager when it didn't exist
00:48:55 T:3033204544 WARNING: Attempted to remove window 10015 from the window manager when it didn't exist
00:48:55 T:3033204544 WARNING: Attempted to remove window 10016 from the window manager when it didn't exist
00:48:55 T:3033204544 WARNING: Attempted to remove window 10017 from the window manager when it didn't exist
00:48:55 T:3033204544 WARNING: Attempted to remove window 10018 from the window manager when it didn't exist
00:48:55 T:3033204544 WARNING: Attempted to remove window 10019 from the window manager when it didn't exist
00:48:55 T:3033204544 WARNING: Attempted to remove window 10021 from the window manager when it didn't exist
00:48:55 T:3033204544 WARNING: Attempted to remove window 10107 from the window manager when it didn't exist
00:48:55 T:3033204544 WARNING: Attempted to remove window 10115 from the window manager when it didn't exist
00:48:55 T:3033204544 WARNING: Attempted to remove window 10104 from the window manager when it didn't exist
00:48:55 T:3033204544  NOTICE: closing down remote control service
00:48:55 T:3033204544  NOTICE: unload sections
00:48:55 T:3033204544  NOTICE: application stopped...
```

**Comment by scakemyer** [comment]
Did you downloaded the big zip file from the releases page? If so, here's the thing about daemon crashes: we don't get any debug logs back (yet). But if you did get the right zip, this might have to do with the platform detection changes I made, although it shouldn't have affected Linux since the logic is the same for it... I'll double-check nonetheless. Thanks for the report.

**Comment by Filosofos** [comment]
Yes, i downloaded the big zip file from the releases page.
I even installed it from pulsar unofficial repo in case i was missing something, but i had the same error.

**Comment by i96751414** [comment]
Recently I had an issue with ubuntu.. Do the following:
Firstly, install:
```sudo apt-get install libstdc++6```
This should already be installed by default, but try it anyway. If it doesn't solve it, just do the following:
```sudo add-apt-repository ppa:ubuntu-toolchain-r/test ```
```sudo apt-get update```
```sudo apt-get upgrade```
```sudo apt-get dist-upgrade```

Tell me if it worked

**Comment by Filosofos** [comment]
libstdc++6 was already installed by default, so i followed your second advice which worked perfectly.
Thank you very much.
By the way, what was missing and couldn't let Quasar start properly?

**Comment by i96751414** [comment]
I think that an update that ubuntu received broke libstdc++6, which is used by pulsar.

**Comment by Filosofos** [comment]
Thank you for clarifying it!

**Comment by luismva** [comment]
hello,

I have a ubuntu 14.04 with kodi 16 and quaser 9.23, and it still crashes. And I 2 pc with the same linux. The same behavior on both.
I have done the recommendations of i96751414 without success.

Is there anything I am missing?

br
Luis

**Comment by Filosofos** [comment]
It would help if you could provide the log file.

**Comment by luismva** [comment]
ok.
havent found its location yet, but when i do i will send it

**Comment by Filosofos** [comment]
Look [here](http://kodi.wiki/view/Log_file/Advanced)
$HOME/.kodi/temp/kodi.log

**Comment by luismva** [comment]
thanks

**Comment by radinsky** [comment]
Helped for me as mentioned before:

```
sudo apt-get install libstdc++6
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
```
