### ISSUE TITLE
Quasar freezes in the "Opening Stream" screen when any title is selected

### ISSUE THREAD

**Issue by Verzwei** [scakemyer/plugin.video.quasar#500]
Hello, Devs. First of all I would like to thank you for your hard work developing this awesome extension (which I unfortunately still hadn't the chance to use)! I just installed Quasar and when I select any title, the "Opening Stream" dialog appears and after a couple of moments it freezes Kodi until I stop the process on the Task Manager.

I believe this is the part of the log that describes the error:
```
18:15:42 T:140629745055488  NOTICE: [plugin.video.quasar] System information: linux_x64 4.4.0-22-generic
18:15:42 T:140629745055488  NOTICE: [plugin.video.quasar] Kodi build version: 17.0-ALPHA2 Git:cbb432a
18:15:42 T:140629745055488  NOTICE: [plugin.video.quasar] OS type: Linux
18:15:42 T:140629745055488  NOTICE: [plugin.video.quasar] uname: ('Linux', 'matheus-Xubuntu58B7', '4.4.0-22-generic', '#39-Ubuntu SMP Thu May 5 16:53:32 UTC 2016', 'x86_64', 'x86_64')
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar] Traceback (most recent call last):
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]   File "/home/matheus/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 112, in run
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]     data = _json(url)
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]   File "/home/matheus/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 48, in _json
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]     return opener.open(url, data, timeout)
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 429, in open
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]     response = self._open(req, data)
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]     '_open', req)
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]     result = func(*args)
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]     return self.do_open(httplib.HTTPConnection, req)
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]     r = h.getresponse(buffering=True)
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]     response.begin()
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/httplib.py", line 453, in begin
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]     version, status, reason = self._read_status()
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]     raise BadStatusLine(line)
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar] BadStatusLine: ''
18:15:42 T:140629040428800   ERROR: [plugin.video.quasar]
```

I'm not sure if this is a issue caused by any lack of dependencies in my system or if it's caused by Quasar itself. Hope it helps!

**Comment by scakemyer** [comment]
Kodi 17-alpha2 back then... reopen if needed.
