### ISSUE TITLE
OSX 10.10: error when clicking update library

### ISSUE THREAD

**Issue by send2moran** [scakemyer/plugin.video.quasar#528]
HTTPError: HTTP Error 404: Not Found

```
13:48:52 T:140735284072448   DEBUG: RunScriptWithParams - calling plugin Quasar('plugin://plugin.video.quasar/library/update','-1','')
13:48:52 T:123145303453696   DEBUG: Thread LanguageInvoker start, auto delete: false
13:48:52 T:123145303453696    INFO: initializing python engine.
13:48:52 T:123145303453696   DEBUG: CPythonInvoker(12, /Users/Helmano/Library/Application Support/Kodi/addons/plugin.video.quasar/navigation.py): start processing
13:48:52 T:123145303453696   DEBUG: -->Python Interpreter Initialized<--
13:48:52 T:123145303453696   DEBUG: CPythonInvoker(12, /Users/Helmano/Library/Application Support/Kodi/addons/plugin.video.quasar/navigation.py): the source file to load is "/Users/Helmano/Library/Application Support/Kodi/addons/plugin.video.quasar/navigation.py"
13:48:52 T:123145303453696   DEBUG: CPythonInvoker(12, /Users/Helmano/Library/Application Support/Kodi/addons/plugin.video.quasar/navigation.py): setting the Python path to /Users/Helmano/Library/Application Support/Kodi/addons/plugin.video.quasar:/Applications/Kodi.app/Contents/Libraries:/Applications/Kodi.app/Contents/Libraries/lib/python26.zip:/Applications/Kodi.app/Contents/Libraries/lib/python2.6:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-darwin:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-mac:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-mac/lib-scriptpackages:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-tk:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-old:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-dynload:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/site-packages:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/site-packages/PIL
13:48:52 T:123145303453696   DEBUG: CPythonInvoker(12, /Users/Helmano/Library/Application Support/Kodi/addons/plugin.video.quasar/navigation.py): entering source directory /Users/Helmano/Library/Application Support/Kodi/addons/plugin.video.quasar
13:48:52 T:123145303453696   DEBUG: CPythonInvoker(12, /Users/Helmano/Library/Application Support/Kodi/addons/plugin.video.quasar/navigation.py): instantiating add-on using automatically obtained id of "plugin.video.quasar" dependent on version 2.1.0 of the xbmc.python api
13:48:52 T:123145303453696  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/library/update from ['plugin://plugin.video.quasar/library/update', '-1', '']
13:48:52 T:123145324535808  NOTICE: [plugin.video.quasar] [GIN] 2016/08/09 - 13:48:52 |[97;43m 404 [0m|      51.093µs | 127.0.0.1 |[97;44m  [0m GET     /library/update
13:48:52 T:123145303453696   ERROR: [plugin.video.quasar] Traceback (most recent call last):
13:48:52 T:123145303453696   ERROR: [plugin.video.quasar]   File "/Users/Helmano/Library/Application Support/Kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 112, in run
13:48:52 T:123145303453696   ERROR: [plugin.video.quasar]     data = _json(url)
13:48:52 T:123145303453696   ERROR: [plugin.video.quasar]   File "/Users/Helmano/Library/Application Support/Kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 48, in _json
13:48:52 T:123145303453696   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
13:48:52 T:123145303453696   ERROR: [plugin.video.quasar]   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/urllib2.py", line 126, in url open
13:48:52 T:123145303453696   ERROR: [plugin.video.quasar]   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/urllib2.py", line 397, in open
13:48:52 T:123145303453696   ERROR: [plugin.video.quasar]   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/urllib2.py", line 510, in http_response
13:48:52 T:123145303453696   ERROR: [plugin.video.quasar]   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/urllib2.py", line 435, in error
13:48:52 T:123145303453696   ERROR: [plugin.video.quasar]   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/urllib2.py", line 369, in _call_chain
13:48:52 T:123145303453696   ERROR: [plugin.video.quasar]   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/urllib2.py", line 518, in http_error_default
13:48:52 T:123145303453696   ERROR: [plugin.video.quasar] HTTPError: HTTP Error 404: Not Found
13:48:52 T:123145303453696   ERROR: [plugin.video.quasar]
```

**Comment by scakemyer** [comment]
#542
