### ISSUE TITLE
macOS Sierra: Quasar Crashes 3x then Aborts Upon Opening Kodi

### ISSUE THREAD

**Issue by 5Coates** [scakemyer/plugin.video.quasar#529]
I'm having difficulty installing/running Quasar on my MacBookPro. Whenever I start up Kodi, it shows "Quasar has crashed, restarting..." multiple times before it states "Quasar has crashed too many times, aborting..."  I've tried totally uninstalling Kodi (Application Support folder included) and starting from scratch to no avail. I also tried using the Isengard (15.2) version of Kodi and experienced the same issue. 

**System/Application Information**
MacBook Pro (Retina, 15 in, Mid 2004)
Mac OS: Version 10.12 Beta (macOS Sierra)
Build: Kodi 16.1 (24 April 2016)
Qusar Version 0.9.34

Here are the logs:

```
13:12:02 T:140736770462656  NOTICE: special://profile/ is mapped to: special://masterprofile/
13:12:02 T:140736770462656  NOTICE: -----------------------------------------------------------------------
13:12:02 T:140736770462656  NOTICE: Starting Kodi (16.1 Git:2016-04-24-c327c53). Platform: OS X x86 64-bit
13:12:02 T:140736770462656  NOTICE: Using Release Kodi x64 build
13:12:02 T:140736770462656  NOTICE: Kodi compiled Apr 24 2016 by Clang 6.0 (clang-600.0.56) for OS X x86 64-bit version 10.7.0 (1070)
13:12:02 T:140736770462656  NOTICE: Running on Apple Inc. MacBookPro11,2 with OS X 10.12, kernel: Darwin x86 64-bit version 16.0.0
13:12:02 T:140736770462656  NOTICE: Host CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz, 8 cores available
13:12:02 T:140736770462656  NOTICE: special://xbmc/ is mapped to: /Applications/Kodi.app/Contents/Resources/Kodi
13:12:02 T:140736770462656  NOTICE: special://xbmcbin/ is mapped to: /Applications/Kodi.app/Contents/Resources/Kodi
13:12:02 T:140736770462656  NOTICE: special://masterprofile/ is mapped to: /Users/5Coates/Library/Application Support/Kodi/userdata
13:12:02 T:140736770462656  NOTICE: special://home/ is mapped to: /Users/5Coates/Library/Application Support/Kodi
13:12:02 T:140736770462656  NOTICE: special://temp/ is mapped to: /Users/5Coates/.kodi/temp
13:12:02 T:140736770462656  NOTICE: special://frameworks/ is mapped to: /Applications/Kodi.app/Contents/Libraries
13:12:02 T:140736770462656  NOTICE: The executable running is: /Applications/Kodi.app/Contents/MacOS/Kodi
13:12:02 T:140736770462656  NOTICE: Local hostname: cinco-coates.local
13:12:02 T:140736770462656  NOTICE: Log File is located: /Users/5Coates/Library/Logs/kodi.log
13:12:02 T:140736770462656  NOTICE: -----------------------------------------------------------------------
13:12:02 T:140736770462656  NOTICE: load settings...
13:12:02 T:140736770462656 WARNING: CSettingString: unknown options filler "timezonecountries" of "locale.timezonecountry"
13:12:02 T:140736770462656 WARNING: CSettingString: unknown options filler "timezones" of "locale.timezone"
13:12:02 T:140736770462656  NOTICE: Found 1 Lists of Devices
13:12:02 T:140736770462656  NOTICE: Enumerated DARWINOSX devices:
13:12:02 T:140736770462656  NOTICE:     Device 1
13:12:02 T:140736770462656  NOTICE:         m_deviceName      : default
13:12:02 T:140736770462656  NOTICE:         m_displayName     : Default
13:12:02 T:140736770462656  NOTICE:         m_displayNameExtra: Built-in Output
13:12:02 T:140736770462656  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
13:12:02 T:140736770462656  NOTICE:         m_channels        : FL,FR
13:12:02 T:140736770462656  NOTICE:         m_sampleRates     : 96000,88200,48000,44100
13:12:02 T:140736770462656  NOTICE:         m_dataFormats     : AE_FMT_S24LE3,AE_FMT_S16LE,AE_FMT_FLOAT
13:12:02 T:140736770462656  NOTICE:     Device 2
13:12:02 T:140736770462656  NOTICE:         m_deviceName      : Built-in Output:stream0
13:12:02 T:140736770462656  NOTICE:         m_displayName     : Built-in Output
13:12:02 T:140736770462656  NOTICE:         m_displayNameExtra: Internal Speakers
13:12:02 T:140736770462656  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
13:12:02 T:140736770462656  NOTICE:         m_channels        : FL,FR
13:12:02 T:140736770462656  NOTICE:         m_sampleRates     : 96000,88200,48000,44100
13:12:02 T:140736770462656  NOTICE:         m_dataFormats     : AE_FMT_S24LE3,AE_FMT_S16LE,AE_FMT_FLOAT
13:12:02 T:140736770462656  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
13:12:02 T:140736770462656  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
13:12:02 T:140736770462656  NOTICE: Default DVD Player: dvdplayer
13:12:02 T:140736770462656  NOTICE: Default Video Player: dvdplayer
13:12:02 T:140736770462656  NOTICE: Default Audio Player: paplayer
13:12:02 T:140736770462656  NOTICE: Disabled debug logging due to GUI setting. Level 0.
13:12:02 T:140736770462656  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
13:12:02 T:140736770462656  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
13:12:02 T:140736770462656  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
13:12:02 T:140736770462656  NOTICE: Loaded playercorefactory configuration
13:12:02 T:140736770462656  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
13:12:02 T:140736770462656  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
13:12:02 T:123145564004352  NOTICE: virtual bool CAESinkDARWINOSX::Initialize(AEAudioFormat &, std::string &): Opening default device Built-in Output
13:12:02 T:140736770462656  NOTICE: Running database version Addons20
13:12:02 T:140736770462656  NOTICE: ADDONS: Using repository repository.exodus
13:12:02 T:140736770462656  NOTICE: ADDONS: Using repository repository.xbmc.org
13:12:02 T:140736770462656  NOTICE: Setup SDL
13:12:02 T:140736770462656  NOTICE: Display 0 has name Color LCD
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 1440 x 900 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 720 x 450 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 1920 x 1200 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 1680 x 1050 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 1280 x 800 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 1024 x 640 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 840 x 525 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 2880 x 1800 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 1440 x 900 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 2560 x 1600 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 2048 x 1280 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 1024 x 768 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 800 x 600 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 640 x 480 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 1680 x 1050 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Found possible resolution for display 0 with 1280 x 800 @ 60.000000 Hz
13:12:02 T:140736770462656  NOTICE: Checking resolution 15
13:12:02 T:140736770462656  NOTICE: GL_VENDOR = Intel Inc.
13:12:02 T:140736770462656  NOTICE: GL_RENDERER = Intel Iris Pro OpenGL Engine
13:12:02 T:140736770462656  NOTICE: GL_VERSION = 2.1 INTEL-10.18.63
13:12:02 T:140736770462656  NOTICE: GL_SHADING_LANGUAGE_VERSION = 1.20
13:12:02 T:140736770462656  NOTICE: GL_EXTENSIONS = GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_separate_stencil GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod
13:12:03 T:140736770462656  NOTICE: Running database version Addons20
13:12:03 T:140736770462656  NOTICE: Running database version ViewModes6
13:12:03 T:140736770462656  NOTICE: Running database version Textures13
13:12:03 T:140736770462656  NOTICE: Running database version MyMusic56
13:12:03 T:140736770462656  NOTICE: Running database version MyVideos99
13:12:03 T:140736770462656  NOTICE: Running database version TV29
13:12:03 T:140736770462656  NOTICE: Running database version Epg11
13:12:03 T:140736770462656  NOTICE: start dvd mediatype detection
13:12:03 T:140736770462656 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
13:12:03 T:140736770462656  NOTICE: ActiveAE DSP - starting
13:12:03 T:140736770462656  NOTICE: initialize done
13:12:03 T:140736770462656  NOTICE: Running the application...
13:12:03 T:140736770462656  NOTICE: starting zeroconf publishing
13:12:03 T:140736770462656  NOTICE: starting upnp client
13:12:03 T:123145572130816  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
13:12:03 T:123145572130816  NOTICE: UDP: Listening on port 9777
13:12:03 T:123145574891520  NOTICE: [plugin.video.quasar] quasar: starting jsonrpc service
13:12:03 T:123145575428096  NOTICE: [plugin.video.quasar] quasard: starting quasard
13:12:03 T:123145575428096  NOTICE: [plugin.video.quasar] Deleting stale files set([])
13:12:03 T:123145575428096  NOTICE: [plugin.video.quasar] System information: darwin_x64 16.0.0
13:12:03 T:123145575428096  NOTICE: [plugin.video.quasar] Kodi build version: 16.1 Git:2016-04-24-c327c53
13:12:03 T:123145575428096  NOTICE: [plugin.video.quasar] OS type: Darwin
13:12:03 T:123145575428096  NOTICE: [plugin.video.quasar] uname: ('Darwin', 'cinco-coates.local', '16.0.0', 'Darwin Kernel Version 16.0.0: Thu Aug 18 18:25:11 PDT 2016; root:xnu-3789.1.29~5/RELEASE_X86_64', 'x86_64', 'i386')
13:12:06 T:123145575428096  NOTICE: [plugin.video.quasar] quasard: starting quasard
13:12:06 T:123145575428096  NOTICE: [plugin.video.quasar] Deleting stale files set([])
13:12:06 T:123145575428096  NOTICE: [plugin.video.quasar] System information: darwin_x64 16.0.0
13:12:06 T:123145575428096  NOTICE: [plugin.video.quasar] Kodi build version: 16.1 Git:2016-04-24-c327c53
13:12:06 T:123145575428096  NOTICE: [plugin.video.quasar] OS type: Darwin
13:12:06 T:123145575428096  NOTICE: [plugin.video.quasar] uname: ('Darwin', 'cinco-coates.local', '16.0.0', 'Darwin Kernel Version 16.0.0: Thu Aug 18 18:25:11 PDT 2016; root:xnu-3789.1.29~5/RELEASE_X86_64', 'x86_64', 'i386')
13:12:09 T:123145575428096  NOTICE: [plugin.video.quasar] quasard: starting quasard
13:12:09 T:123145575428096  NOTICE: [plugin.video.quasar] Deleting stale files set([])
13:12:09 T:123145575428096  NOTICE: [plugin.video.quasar] System information: darwin_x64 16.0.0
13:12:09 T:123145575428096  NOTICE: [plugin.video.quasar] Kodi build version: 16.1 Git:2016-04-24-c327c53
13:12:09 T:123145575428096  NOTICE: [plugin.video.quasar] OS type: Darwin
13:12:09 T:123145575428096  NOTICE: [plugin.video.quasar] uname: ('Darwin', 'cinco-coates.local', '16.0.0', 'Darwin Kernel Version 16.0.0: Thu Aug 18 18:25:11 PDT 2016; root:xnu-3789.1.29~5/RELEASE_X86_64', 'x86_64', 'i386')
13:12:13 T:123145558638592  NOTICE: [plugin.video.quasar] System information: darwin_x64 16.0.0
13:12:13 T:123145558638592  NOTICE: [plugin.video.quasar] Kodi build version: 16.1 Git:2016-04-24-c327c53
13:12:13 T:123145558638592  NOTICE: [plugin.video.quasar] OS type: Darwin
13:12:13 T:123145558638592  NOTICE: [plugin.video.quasar] uname: ('Darwin', 'cinco-coates.local', '16.0.0', 'Darwin Kernel Version 16.0.0: Thu Aug 18 18:25:11 PDT 2016; root:xnu-3789.1.29~5/RELEASE_X86_64', 'x86_64', 'i386')
13:12:13 T:140736770462656   ERROR: GetDirectory - Error getting plugin://plugin.video.quasar/
13:12:13 T:140736770462656   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/) failed
13:12:15 T:140736770462656   ERROR: Unable to activate the previous window
```

Anybody have any ideas? The Google and Forum searches are coming up dry.  Thanks!

**Comment by scakemyer** [comment]
There's very little debug info here unfortunately, looks like macOS is just preventing Quasar from launching altogether, I'm guessing because of Gatekeeper.

**Comment by zukove** [comment]
Hello. Having the same issue with the original release. scakemyer, are you planning on making Quasar work with MacOS Sierra? Thanks.

**Comment by zukove** [comment]
Also, important to note that I have disabled the gatekeeper.

**Comment by PedroMD** [comment]
Same thing happening to me after upgrading to macOS Sierra. Will try to upload some logs later on.

**Comment by Pinhastest** [comment]
Same problem here with gatekeeper disabled

**Comment by PedroMD** [comment]
Here is my log (same as OP, basically...): http://pastebin.com/8Y4jYg6d

**Comment by ajimix** [comment]
Same problem here, with Sierra and Gatekeeper disabled

**Comment by pablopda** [comment]
Same problem here. Anyone find a workaround ?

**Comment by Rogiel** [comment]
From what I can tell this seems related to UPX packing.

https://github.com/upx/upx/issues/4

**Comment by Rogiel** [comment]
As a workaround you can replace the upx packed quasar deamon with a unpacked version. 

The file is located at: **/Users/_\<your username\>_/Library/Application Support/Kodi/addons/plugin.video.quasar/resources/bin/darwin_x64**

and replace **quasar** executable with this [quasar.zip](https://github.com/scakemyer/plugin.video.quasar/files/517733/quasar.zip).

Also, if you do not want to trust a binary on the internet (and you shouldn't) you can recompile UPX and manually unpack the file. You must do so with the **devel** branch.

```````
git clone https://github.com/upx/upx.git && cd upx
git checkout devel
git submodule update --init --recursive
make all CXX=clang CXXFLAGS="-stdlib=libc++ -funsigned-char -lc++"
./src/upx.out -d /Users/<your username>/Library/Application Support/Kodi/addons/plugin.video.quasar/resources/bin/darwin_x64/quasar
```````

Should be enough. Unfortunately, the unpacked binary is significantly larger (about 3x larger). If its OK to use the unpacked binary, I can submit a pull request containing the unpacked binary.

**Comment by zukove** [comment]
Dis you test in with Sierra? Can you please confirm tha it works? Can I upgrade?

**Comment by Rogiel** [comment]
@zukove yes, it is working fine with the unpacked executable.

**Comment by zukove** [comment]
@Rogiel Thank you! it works great... very much appreciated :)

**Comment by giwrgos88** [comment]
@Rogiel I have donwloaded the zip file and added it in "darwin_x64" folder but still getting the same error

**Comment by zukove** [comment]
@giwrgos88 did you extract the zip?

**Comment by giwrgos88** [comment]
@zukove yes

**Comment by Emasoft** [comment]
Same problem here with Mac OS Sierra. I tried the quasar.zip unpacked in the folder darwin_x64, but Quasar still crashes at startup.

**Comment by Rogiel** [comment]
Can you manually open the binary? It should print something like that:

``````
INFO  main         ▶ main             
INFO  main         ▶ main             ________
INFO  main         ▶ main             \_____  \  __ _______    ___________ _______
INFO  main         ▶ main              /  / \  \|  |  \__  \  /  ___/\__  \\_  __ \
INFO  main         ▶ main             /   \_/.  \  |  // __ \_\___ \  / __ \|  | \/
INFO  main         ▶ main             \_____\ \_/____/(____  /____  >(____  /__|
INFO  main         ▶ main                    \__>          \/     \/      \/
INFO  main         ▶ main             
INFO  main         ▶ main             Version: "v0.9.35" Go: go1.7.1
``````

If it does not, maybe GateKeeper is complaining about the lack of digital signatures on the executable or the executable does not have executable permission. Try a `chmod +x <file>`

**Comment by giwrgos88** [comment]
INFO  main         ▶ main             
INFO  main         ▶ main             ________
INFO  main         ▶ main             \_____  \  __ _______    ___________ _______
INFO  main         ▶ main              /  / \  \|  |  \__  \  /  ___/\__  \\_  __ \
INFO  main         ▶ main             /   \_/.  \  |  // __ \_\___ \  / __ \|  | \/
INFO  main         ▶ main             \_____\ \_/____/(____  /____  >(____  /__|
INFO  main         ▶ main                    \__>          \/     \/      \/
INFO  main         ▶ main             
INFO  main         ▶ main             Version: "v0.9.35" Go: go1.7.1
INFO  config       ▶ Reload           Reloading configuration...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4157fcc]

goroutine 1 [running]:
panic(0x4a029a0, 0xc42000c0c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/scakemyer/quasar/xbmc.executeJSONRPCEx(0x4aadff4, 0xc, 0x49b20a0, 0xc42024c000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/scakemyer/quasar/xbmc/jsonrpc.go:62 +0xcc
github.com/scakemyer/quasar/xbmc.GetAddonInfo(0xc420016180)
	/go/src/github.com/scakemyer/quasar/xbmc/xbmcaddon.go:24 +0xa1
github.com/scakemyer/quasar/config.Reload(0xc420017560)
	/go/src/github.com/scakemyer/quasar/config/config.go:82 +0xf6
main.main()
	/go/src/github.com/scakemyer/quasar/main.go:84 +0x40d
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by giwrgos88** [comment]
Now it worked

**Comment by PedroMD** [comment]
@Rogiel's [solution](https://github.com/scakemyer/plugin.video.quasar/issues/529#issuecomment-252426940) worked fine! ;)

**Comment by scakemyer** [comment]
Will be fixed in the next release, with a now much bigger binary for macOS. Until then @Rogiel's workaround should do.

**Comment by Steppenwolf-** [comment]
It works on Sierra. Thanks
