### ISSUE TITLE
OSX 10.7.4 Crashes with Navigation error: URLError(gaierror(7,'no address associated with hostname'.),)

### ISSUE THREAD

**Issue by mpikosdimitris** [scakemyer/plugin.video.quasar#545]
Hey dude,
i get this error message after quasar starts and i'm trying to open the addon : 

> Navigation error: URLError(gaierror(7,'no address associated with hostname'.),)

It's a fresh installation on 10.7.4 and Kodi 16.1.

```
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m________
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m\_____  \  __ _______    ___________ _______
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m /  / \  \|  |  \__  \  /  ___/\__  \\_  __ \
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m/   \_/.  \  |  // __ \_\___ \  / __ \|  | \/
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m\_____\ \_/____/(____  /____  >(____  /__|
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m       \__>          \/     \/      \/
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0m
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0mVersion: "v0.9.35" Go: go1.7.1
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  config       ▶ Reload           [0mReloading configuration...
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0mAddon: plugin.video.quasar v0.9.35
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  btservice    ▶ configure        [0mSetting Session settings...
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  btservice    ▶ configure        [0mSetting Encryption settings...
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  tmdb         ▶ CheckApiKey      [0mChecking TMDB API key...
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] INFO  btservice    ▶ alertsConsumer   [0mConsuming alerts...
22:59:29 T:4714692608  NOTICE: [plugin.video.quasar] [32mNOTI  libtorrent   ▶ logAlerts        [0mexternal_ip_alert: external IP received: 2.85.143.179
22:59:30 T:4714692608  NOTICE: [plugin.video.quasar] [32mNOTI  tmdb         ▶ CheckApiKey      [0mTMDB API key check passed, using ae4bd1b...
22:59:30 T:4714692608  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0mUpdating Kodi Addon Repositories
22:59:30 T:4714156032  NOTICE: [plugin.video.quasar] Resetting RPC objects...
22:59:30 T:4724748288   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
22:59:30 T:4724748288   ERROR: CCurlFile::Open failed with code 0 for http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml.md5
22:59:30 T:4724748288   ERROR: Open - failed to open source <http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml.md5>
22:59:30 T:4724748288   ERROR: CRepositoryUpdateJob[repository.quasar] failed read checksum for directory 'http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml'
22:59:33 T:4734812160  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/ from ['plugin://plugin.video.quasar/', '1', '']
22:59:33 T:4734812160   ERROR: [plugin.video.quasar] Traceback (most recent call last):
22:59:33 T:4734812160   ERROR: [plugin.video.quasar]   File "/Users/dimitris/Library/Application Support/Kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 112, in run
22:59:33 T:4734812160   ERROR: [plugin.video.quasar]     data = _json(url)
22:59:33 T:4734812160   ERROR: [plugin.video.quasar]   File "/Users/dimitris/Library/Application Support/Kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 48, in _json
22:59:33 T:4734812160   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
22:59:33 T:4734812160   ERROR: [plugin.video.quasar]   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/urllib2.py", line 126, in urlopen
22:59:33 T:4734812160   ERROR: [plugin.video.quasar]   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/urllib2.py", line 391, in open
22:59:33 T:4734812160   ERROR: [plugin.video.quasar]   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/urllib2.py", line 409, in _open
22:59:33 T:4734812160   ERROR: [plugin.video.quasar]   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/urllib2.py", line 369, in _call_chain
22:59:33 T:4734812160   ERROR: [plugin.video.quasar]   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/urllib2.py", line 1161, in http_open
22:59:33 T:4734812160   ERROR: [plugin.video.quasar]   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/urllib2.py", line 1136, in do_open
22:59:33 T:4734812160   ERROR: [plugin.video.quasar] URLError: <urlopen error [Errno 7] no address associated with hostname.>
22:59:33 T:4734812160   ERROR: [plugin.video.quasar]
22:59:33 T:4445874528   ERROR: GetDirectory - Error getting plugin://plugin.video.quasar/
22:59:33 T:4445874528   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/) failed
22:59:41 T:4445874528   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
22:59:41 T:4579815424  NOTICE: Executing with args: {'mode': 'main'}
22:59:45 T:4702736384   ERROR: Unable to find plugin
22:59:45 T:4445874528   ERROR: GetDirectory - Error getting plugin://
22:59:45 T:4445874528   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
22:59:46 T:4445874528   ERROR: Unable to activate the previous window
22:59:48 T:4445874528  NOTICE: Storing total System Uptime
22:59:48 T:4445874528  NOTICE: Saving settings
22:59:48 T:4445874528  NOTICE: stop all
22:59:48 T:4445874528  NOTICE: stop player
22:59:48 T:4445874528  NOTICE: ES: Stopping event server
22:59:48 T:4445874528  NOTICE: stopping upnp
22:59:48 T:4445874528  NOTICE: stopping zeroconf publishing
22:59:48 T:4445874528  NOTICE: WebServer: Stopped the webserver
22:59:49 T:4706217984  NOTICE: ES: UDP Event server stopped
22:59:49 T:4445874528  NOTICE: stop dvd detect media
22:59:49 T:4445874528  NOTICE: stop sap announcement listener
22:59:49 T:4445874528  NOTICE: clean cached files!
22:59:49 T:4445874528  NOTICE: unload skin
22:59:49 T:4687609856  NOTICE: DudeHere Common Routines Service: Service stopping...
22:59:49 T:4688146432  NOTICE: 1Channel: Service: shutting down...
22:59:54 T:4445874528   ERROR: CPythonInvoker(5, /Users/dimitris/Library/Application Support/Kodi/addons/script.module.axel.downloader/default.py): script didn't stop in 5 seconds - let's kill it
22:59:55 T:4689219584  NOTICE: [plugin.video.quasar] quasar: exiting quasard
22:59:55 T:4714156032  NOTICE: [plugin.video.quasar] quasar: exiting jsonrpc service
22:59:55 T:4686536704  NOTICE: [plugin.video.quasar] quasard: exiting quasard daemon
22:59:55 T:4686536704  NOTICE: [plugin.video.quasar] quasard: quasard daemon exited
22:59:58 T:4445874528  NOTICE: stopped
22:59:58 T:4445874528  NOTICE: destroy
22:59:58 T:4445874528  NOTICE: closing down remote control service
22:59:58 T:4445874528  NOTICE: unload sections
22:59:59 T:4445874528  NOTICE: special://profile/ is mapped to: special://masterprofile/
22:59:59 T:4445874528  NOTICE: destroy
22:59:59 T:4445874528 WARNING: Attempted to remove window 10013 from the window manager when it didn't exist
22:59:59 T:4445874528 WARNING: Attempted to remove window 10014 from the window manager when it didn't exist
22:59:59 T:4445874528 WARNING: Attempted to remove window 10015 from the window manager when it didn't exist
22:59:59 T:4445874528 WARNING: Attempted to remove window 10016 from the window manager when it didn't exist
22:59:59 T:4445874528 WARNING: Attempted to remove window 10017 from the window manager when it didn't exist
22:59:59 T:4445874528 WARNING: Attempted to remove window 10018 from the window manager when it didn't exist
22:59:59 T:4445874528 WARNING: Attempted to remove window 10019 from the window manager when it didn't exist
22:59:59 T:4445874528 WARNING: Attempted to remove window 10021 from the window manager when it didn't exist
22:59:59 T:4445874528 WARNING: Attempted to remove window 10107 from the window manager when it didn't exist
22:59:59 T:4445874528 WARNING: Attempted to remove window 10115 from the window manager when it didn't exist
22:59:59 T:4445874528 WARNING: Attempted to remove window 10104 from the window manager when it didn't exist
22:59:59 T:4445874528  NOTICE: closing down remote control service
22:59:59 T:4445874528  NOTICE: unload sections
22:59:59 T:4445874528  NOTICE: application stopped...

```

**Comment by scakemyer** [comment]
Got it working? It doesn't make any sense that OSX wouldn't know how to reach `localhost`...
