### ISSUE TITLE
Plugin not loading: IOerror 22 invalid argument

### ISSUE THREAD

**Issue by basekk** [scakemyer/plugin.video.quasar#549]
Hi all, hi scakemyer,

recently I get an error message, when I try to start Quasar on Kodi (running on a FireTV stick).
The message is OError: [Errno 22] Invalid argument
I had a look into the log file. But unfortunately I do not understand how to solve this. It seems to be an issue with the checksum (?)

Remote control option is enabled, I tried un- and reinstalls from zip files. Restarted KODI several times in between. But the error message remains and Quasar is not starting up.

The log file can be seen below.

Thanks in advance for any help!

```
19:06:47 T:1103875160  NOTICE: special://profile/ is mapped to: special://masterprofile/
19:06:47 T:1103875160  NOTICE: -----------------------------------------------------------------------
19:06:47 T:1103875160  NOTICE: Starting Kodi (16.0 Git:2016-02-20-a5f3a99). Platform: Android ARM 32-bit
19:06:47 T:1103875160  NOTICE: Using Release Kodi x32 build
19:06:47 T:1103875160  NOTICE: Kodi compiled Feb 20 2016 by GCC 4.8.0 for Android ARM 32-bit API level 17 (API level 17)
19:06:47 T:1103875160  NOTICE: Running on Amazon AFTM with Android 5.1.1 API level 22, kernel: Linux ARM 32-bit version 3.0.31+
19:06:47 T:1103875160  NOTICE: FFmpeg version: 2.8.6-kodi-2.8.6-Jarvis-16.0
19:06:47 T:1103875160  NOTICE: Host CPU: ARMv7 Processor rev 0 (v7l), 2 cores available
19:06:47 T:1103875160  NOTICE: Product: montoya, Device: montoya, Board: capri - Manufacturer: Amazon, Brand: Amazon, Model: AFTM, Hardware: montoya
19:06:47 T:1103875160  NOTICE: External storage path = /storage/emulated/0; status = ok
19:06:47 T:1103875160  NOTICE: ARM Features: Neon enabled
19:06:47 T:1103875160  NOTICE: special://xbmc/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
19:06:47 T:1103875160  NOTICE: special://xbmcbin/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
19:06:47 T:1103875160  NOTICE: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
19:06:47 T:1103875160  NOTICE: special://home/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
19:06:47 T:1103875160  NOTICE: special://temp/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
19:06:47 T:1103875160  NOTICE: The executable running is:
19:06:47 T:1103875160  NOTICE: Local hostname: localhost
19:06:47 T:1103875160  NOTICE: Log File is located: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
19:06:47 T:1103875160  NOTICE: -----------------------------------------------------------------------
19:06:47 T:1103875160  NOTICE: load settings...
19:06:47 T:1103875160   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/settings.xml
19:06:47 T:1103875160 WARNING: CSettingInt: unknown options filler "audiocdactions" of "audiocds.autoaction"
19:06:47 T:1103875160   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/android.xml
19:06:47 T:1103875160   DEBUG: AESinkAUDIOTRACK - 44100 supported
19:06:47 T:1103875160   DEBUG: AESinkAUDIOTRACK - 48000 supported
19:06:47 T:1103875160   DEBUG: AESinkAUDIOTRACK - 96000 supported
19:06:47 T:1103875160  NOTICE: Found 1 Lists of Devices
19:06:47 T:1103875160  NOTICE: Enumerated AUDIOTRACK devices:
19:06:47 T:1103875160  NOTICE:     Device 1
19:06:47 T:1103875160  NOTICE:         m_deviceName      : AudioTrack
19:06:47 T:1103875160  NOTICE:         m_displayName     : android
19:06:47 T:1103875160  NOTICE:         m_displayNameExtra: audiotrack
19:06:47 T:1103875160  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
19:06:47 T:1103875160  NOTICE:         m_channels        : FL,FR,FC,LFE,BL,BR,SL,SR
19:06:47 T:1103875160  NOTICE:         m_sampleRates     : 48000,44100,48000,96000
19:06:47 T:1103875160  NOTICE:         m_dataFormats     : AE_FMT_S16LE,AE_FMT_AC3,AE_FMT_DTS
19:06:47 T:1103875160   DEBUG: CSkinSettings: no <skinsettings> tag found
19:06:47 T:1103875160  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
19:06:47 T:1103875160  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
19:06:47 T:1103875160  NOTICE: Default DVD Player: dvdplayer
19:06:47 T:1103875160  NOTICE: Default Video Player: dvdplayer
19:06:47 T:1103875160  NOTICE: Default Audio Player: paplayer
19:06:47 T:1103875160  NOTICE: Disabled debug logging due to GUI setting. Level 0.
19:06:47 T:1103875160  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
19:06:47 T:1103875160  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
19:06:47 T:1103875160  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
19:06:47 T:1103875160  NOTICE: Loaded playercorefactory configuration
19:06:47 T:1103875160  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
19:06:47 T:1103875160  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
19:06:47 T:1103875160  NOTICE: Running database version Addons20
19:06:48 T:1103875160  NOTICE: ADDONS: Using repository repository.xbmchub
19:06:48 T:1103875160  NOTICE: ADDONS: Using repository repository.xbmc.org
19:06:48 T:1103875160  NOTICE: ADDONS: Using repository superrepo.kodi.jarvis.all
19:06:48 T:1103875160  NOTICE: ADDONS: Using repository repo.natko1412
....
19:06:48 T:1103875160  NOTICE: virtual bool CWinSystemEGL::InitWindowSystem(): Using EGL Implementation: android
19:06:48 T:1103875160  NOTICE: CEGLNativeTypeAndroid: Switching to resolution:
19:06:48 T:1103875160  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
19:06:48 T:1103875160  NOTICE: Previous line repeats 1 times.
19:06:48 T:1103875160  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 59.999996 Hz
19:06:48 T:1103875160  NOTICE: Found (1920x1080@59.999996) at 16, setting to RES_DESKTOP at 16
19:06:48 T:1103875160  NOTICE: Checking resolution 16
19:06:48 T:1103875160  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
19:06:48 T:1103875160  NOTICE: CEGLNativeTypeAndroid: Switching to resolution: 1920x1080 @ 60.00 - Full Screen
19:06:48 T:1103875160  NOTICE: GL_VENDOR = Broadcom
19:06:48 T:1103875160  NOTICE: GL_RENDERER = VideoCore IV HW
19:06:48 T:1103875160  NOTICE: GL_VERSION = OpenGL ES 2.0
19:06:48 T:1103875160  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
19:06:48 T:1103875160  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_EXT_debug_marker
19:06:48 T:1103875160  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
19:06:49 T:1103875160 WARNING: Unable to resolve: /libcec.so CECInitialise, reason: undefined symbol: CECInitialise
19:06:49 T:1103875160   ERROR: Unable to resolve exports from dll libcec.so
19:06:49 T:1103875160   ERROR: virtual void PERIPHERALS::CPeripherals::Initialise() - failed to initialise bus cec
19:06:49 T:1103875160  NOTICE: Running database version Addons20
19:06:49 T:1103875160  NOTICE: Running database version ViewModes6
19:06:49 T:1103875160  NOTICE: Running database version Textures13
19:06:49 T:1103875160  NOTICE: Running database version MyMusic56
19:06:49 T:1103875160  NOTICE: Running database version MyVideos99
19:06:49 T:1103875160  NOTICE: Running database version TV29
19:06:49 T:1103875160  NOTICE: Running database version Epg11
19:06:49 T:1103875160 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
19:06:50 T:1384339968  NOTICE: PVRManager - starting up
19:06:50 T:1103875160  NOTICE: ActiveAE DSP - starting
19:06:50 T:1103875160  NOTICE: void CApplication::UpdateLibraries(): Starting video library startup scan
19:06:50 T:1103875160   ERROR: int CScriptInvocationManager::ExecuteAsync(const string&, const AddonPtr&, const std::vectorstd::basic_string<char >&) - Not executing non-existing script /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.navi-x/service.py
19:06:50 T:1103875160  NOTICE: initialize done
19:06:50 T:1103875160  NOTICE: Running the application...
19:06:51 T:1103875160  NOTICE: starting zeroconf publishing
19:06:51 T:1103875160  NOTICE: starting upnp client
19:06:51 T:1401821336  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
19:06:51 T:1401821336  NOTICE: UDP: Listening on port 9777
19:06:51 T:1103875160  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
19:06:51 T:1103875160  NOTICE: GL_VENDOR = Broadcom
19:06:51 T:1103875160  NOTICE: GL_RENDERER = VideoCore IV HW
19:06:51 T:1103875160  NOTICE: GL_VERSION = OpenGL ES 2.0
19:06:51 T:1103875160  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
19:06:51 T:1103875160  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_EXT_debug_marker
19:06:51 T:1384339968  NOTICE: VideoInfoScanner: Starting scan ..
....
19:07:00 T:1411435592  NOTICE: [plugin.video.quasar] quasard: starting quasard
19:07:00 T:1419551024  NOTICE: [plugin.video.quasar] quasar: starting jsonrpc service
19:07:01 T:1411435592  NOTICE: [plugin.video.quasar] Detected binary folder: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/bin/android_arm
19:07:01 T:1411435592  NOTICE: [plugin.video.quasar] Using binary folder: /storage/emulated/legacy/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/bin/android_arm
19:07:02 T:1390670416  NOTICE: Universal - An Addons Toolkit: -watchhistory- -Loading sqlite3 as DB engine version: 3.8.6
19:07:02 T:1411435592   ERROR: [plugin.video.quasar] Traceback (most recent call last):
19:07:02 T:1411435592   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 157, in quasard_thread
19:07:02 T:1411435592   ERROR: [plugin.video.quasar]     proc = start_quasard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
19:07:02 T:1411435592   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 112, in start_quasard
19:07:02 T:1411435592   ERROR: [plugin.video.quasar]     quasar_dir, quasar_binary = get_quasar_binary()
19:07:02 T:1411435592   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 60, in get_quasar_binary
19:07:02 T:1411435592   ERROR: [plugin.video.quasar]     if not os.path.exists(dest_binary_path) or get_quasard_checksum(dest_binary_path) != get_quasard_checksum(binary_path):
19:07:02 T:1411435592   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 27, in get_quasard_checksum
19:07:02 T:1411435592   ERROR: [plugin.video.quasar]     fp.seek(-40, os.SEEK_END)  # we put a sha1 there
19:07:02 T:1411435592   ERROR: [plugin.video.quasar] IOError: [Errno 22] Invalid argument
19:07:02 T:1411435592   ERROR: [plugin.video.quasar]
19:07:02 T:1390670416  NOTICE: Universal - An Addons Toolkit: -watchhistory- -DELETE FROM watch_history WHERE lastwatched < '2016-09-18'
19:07:02 T:1411435592   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/threading.py", line 532, in __bootstrap_inner
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/threading.py", line 484, in run
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 157, in quasard_thread
                                                proc = start_quasard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 112, in start_quasard
                                                quasar_dir, quasar_binary = get_quasar_binary()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 60, in get_quasar_binary
                                                if not os.path.exists(dest_binary_path) or get_quasard_checksum(dest_binary_path) != get_quasard_checksum(binary_path):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 27, in get_quasard_checksum
                                                fp.seek(-40, os.SEEK_END)  # we put a sha1 there
                                            IOError: [Errno 22] Invalid argument
19:07:05 T:1437294600  NOTICE: [plugin.video.quasar] System information: android_arm 3.0.31+
19:07:05 T:1437294600  NOTICE: [plugin.video.quasar] Kodi build version: 16.0 Git:2016-02-20-a5f3a99
19:07:05 T:1437294600  NOTICE: [plugin.video.quasar] OS type: Linux
19:07:05 T:1437294600  NOTICE: [plugin.video.quasar] uname: ('Linux', 'localhost', '3.0.31+', '#3 SMP PREEMPT Fri Aug 5 23:30:26 UTC 2016', 'armv7l', '')
19:07:05 T:1103875160   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.quasar/
19:07:05 T:1103875160   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/) failed
19:07:10 T:1389117448   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
```

**Comment by Lampwick** [comment]
I've got the exact same issue

**Comment by nickolayrusev** [comment]
Hello guys, I had the exact same problem with Quasar on Raspberry Pi 2.
 I managed to fix it with the following steps:

1. Uninstall current version of Quasar.
2. Reboot
3. ssh to your device and delete folder /storage/.kodi/userdata/addon_data/plugin.video.quasar
4. Install again Quasar

**Comment by NicholasLAranda** [comment]
I have this same issue. #642 did not solve my issue as it re-directed back here & #657 had no resolution either.

My Kodi does not tell me to restart Kodi.

After uninstalling the addon within Kodi, the folder is not present at the location, or anywhere on my Fire TV.

Reinstalling the addon does not solve the issue.

I have a 3rd gen Fire TV 4K UHD pendant-style.
