### ISSUE TITLE
OS Error 13 : Permission Denied (Matricom Gbox-Q)

### ISSUE THREAD

**Issue by dr1ss** [scakemyer/plugin.video.quasar#575]
Hey guys Quasar won't start on my Matricom Gbox-Q (Kodi 16.2, ARM CPU)

Here is the complete logs :

```
01:07:15 T:18446744072347124480  NOTICE:  special://profile/ is mapped to: special://masterprofile/
01:07:15 T:18446744072347124480  NOTICE:  -----------------------------------------------------------------------
01:07:15 T:18446744072347124480  NOTICE:  Starting Kodi (16.1 Git:2016-04-24-f6ceced). Platform: Android ARM 32-bit
01:07:15 T:18446744072347124480  NOTICE:  Using Release Kodi x32 build
01:07:15 T:18446744072347124480  NOTICE:  Kodi compiled Apr 24 2016 by GCC 4.8.0 for Android ARM 32-bit API level 17 (API level 17)
01:07:15 T:18446744072347124480  NOTICE:  Running on Matricom G-Box Q with Android 5.1.1 API level 22, kernel: Linux ARM 32-bit version 3.10.33
01:07:15 T:18446744072347124480  NOTICE:  FFmpeg version: 2.8.6-kodi-2.8.6-Jarvis-16.0
01:07:15 T:18446744072347124480  NOTICE:  Host CPU: ARMv7 Processor rev 1 (v7l), 4 cores available
01:07:15 T:18446744072347124480  NOTICE:  Product: q, Device: q, Board: n200C - Manufacturer: Matricom, Brand: G-Box, Model: G-Box Q, Hardware: amlogic
01:07:15 T:18446744072347124480  NOTICE:  External storage path = /storage/emulated/0; status = ok
01:07:15 T:18446744072347124480  NOTICE:  ARM Features: Neon enabled
01:07:15 T:18446744072347124480  NOTICE:  special://xbmc/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
01:07:15 T:18446744072347124480  NOTICE:  special://xbmcbin/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
01:07:15 T:18446744072347124480  NOTICE:  special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
01:07:15 T:18446744072347124480  NOTICE:  special://home/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
01:07:15 T:18446744072347124480  NOTICE:  special://temp/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
01:07:15 T:18446744072347124480  NOTICE:  The executable running is:
01:07:15 T:18446744072347124480  NOTICE:  Local hostname: localhost
01:07:15 T:18446744072347124480  NOTICE:  Log File is located: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
01:07:15 T:18446744072347124480  NOTICE:  -----------------------------------------------------------------------
01:07:15 T:18446744072347124480  NOTICE:  load settings...
01:07:16 T:18446744072347124480   DEBUG:  CSettings: loaded settings definition from special://xbmc/system/settings/settings.xml
01:07:16 T:18446744072347124480 WARNING:  CSettingInt: unknown options filler "audiocdactions" of "audiocds.autoaction"
01:07:16 T:18446744072347124480   DEBUG:  CSettings: loaded settings definition from special://xbmc/system/settings/android.xml
01:07:16 T:18446744072347124480  NOTICE:  Found 1 Lists of Devices
01:07:16 T:18446744072347124480  NOTICE:  Enumerated AUDIOTRACK devices:
01:07:16 T:18446744072347124480  NOTICE:      Device 1
01:07:16 T:18446744072347124480  NOTICE:          m_deviceName      : AudioTrack
01:07:16 T:18446744072347124480  NOTICE:          m_displayName     : android
01:07:16 T:18446744072347124480  NOTICE:          m_displayNameExtra: audiotrack
01:07:16 T:18446744072347124480  NOTICE:          m_deviceType      : AE_DEVTYPE_PCM
01:07:16 T:18446744072347124480  NOTICE:          m_channels        : FL,FR,FC,LFE,BL,BR,SL,SR
01:07:16 T:18446744072347124480  NOTICE:          m_sampleRates     : 44100
01:07:16 T:18446744072347124480  NOTICE:          m_dataFormats     : AE_FMT_S16LE
01:07:16 T:18446744072347124480   DEBUG:  CSkinSettings: no <skinsettings> tag found
01:07:16 T:18446744072347124480  NOTICE:  No settings file to load (special://xbmc/system/advancedsettings.xml)
01:07:16 T:18446744072347124480  NOTICE:  No settings file to load (special://masterprofile/advancedsettings.xml)
01:07:16 T:18446744072347124480  NOTICE:  Default DVD Player: dvdplayer
01:07:16 T:18446744072347124480  NOTICE:  Default Video Player: dvdplayer
01:07:16 T:18446744072347124480  NOTICE:  Default Audio Player: paplayer
01:07:16 T:18446744072347124480  NOTICE:  Disabled debug logging due to GUI setting. Level 0.
01:07:16 T:18446744072347124480  NOTICE:  Log level changed to "LOG_LEVEL_NORMAL"
01:07:16 T:18446744072347124480  NOTICE:  CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
01:07:16 T:18446744072347124480  NOTICE:  Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
01:07:16 T:18446744072347124480  NOTICE:  Loaded playercorefactory configuration
01:07:16 T:18446744072347124480  NOTICE:  Loading player core factory settings from special://masterprofile/playercorefactory.xml.
01:07:16 T:18446744072347124480  NOTICE:  special://masterprofile/playercorefactory.xml does not exist. Skipping.
01:07:16 T:18446744072347124480  NOTICE:  Running database version Addons20
01:07:16 T:18446744072347124480  NOTICE:  ADDONS: Using repository repository.exodus
01:07:16 T:18446744072347124480  NOTICE:  ADDONS: Using repository repository.unofficialquasar
01:07:16 T:18446744072347124480  NOTICE:  ADDONS: Using repository repository.shani
01:07:16 T:18446744072347124480  NOTICE:  ADDONS: Using repository repository.xbmc.org
01:07:16 T:18446744072347124480  NOTICE:  ADDONS: Using repository repository.xbmchub
01:07:16 T:18446744072347124480  NOTICE:  virtual bool CWinSystemEGL::InitWindowSystem(): Using EGL Implementation: amlandroid
01:07:16 T:18446744072347124480  NOTICE:  Current resolution: 1920x1080 @ 60.00 - Full Screen
01:07:16 T:18446744072347124480  NOTICE:  Previous line repeats 1 times.
01:07:16 T:18446744072347124480  NOTICE:  Found resolution 1920 x 1080 for display 0 with 720 x 480i @ 60.000000 Hz
01:07:16 T:18446744072347124480  NOTICE:  Found resolution 1920 x 1080 for display 0 with 720 x 480 @ 60.000000 Hz
01:07:16 T:18446744072347124480  NOTICE:  Found resolution 1920 x 1080 for display 0 with 720 x 576i @ 50.000000 Hz
01:07:16 T:18446744072347124480  NOTICE:  Found resolution 1920 x 1080 for display 0 with 720 x 576 @ 50.000000 Hz
01:07:16 T:18446744072347124480  NOTICE:  Found resolution 1920 x 1080 for display 0 with 1280 x 720 @ 60.000000 Hz
01:07:16 T:18446744072347124480  NOTICE:  Found resolution 1920 x 1080 for display 0 with 1920 x 1080i @ 60.000000 Hz
01:07:16 T:18446744072347124480  NOTICE:  Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000000 Hz
01:07:16 T:18446744072347124480  NOTICE:  Found resolution 1920 x 1080 for display 0 with 1280 x 720 @ 50.000000 Hz
01:07:16 T:18446744072347124480  NOTICE:  Found resolution 1920 x 1080 for display 0 with 1920 x 1080i @ 50.000000 Hz
01:07:16 T:18446744072347124480  NOTICE:  Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 50.000000 Hz
01:07:16 T:18446744072347124480  NOTICE:  Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 24.000000 Hz
01:07:16 T:18446744072347124480  NOTICE:  Found (1920x1080@60.000000) at 22, setting to RES_DESKTOP at 16
01:07:16 T:18446744072347124480  NOTICE:  Checking resolution 16
01:07:16 T:18446744072347124480  NOTICE:  GL_VENDOR = ARM
01:07:16 T:18446744072347124480  NOTICE:  GL_RENDERER = Mali-450 MP
01:07:16 T:18446744072347124480  NOTICE:  GL_VERSION = OpenGL ES 2.0
01:07:16 T:18446744072347124480  NOTICE:  GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
01:07:16 T:18446744072347124480  NOTICE:  GL_EXTENSIONS = GL_EXT_debug_marker GL_OES_texture_npot GL_OES_vertex_array_object GL_OES_compressed_ETC1_RGB8_texture GL_EXT_compressed_ETC1_RGB8_sub_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_mapbuffer
01:07:16 T:18446744072347124480  NOTICE:  Current resolution: 1920x1080 @ 60.00 - Full Screen
01:07:16 T:18446744072347124480  NOTICE:  Running database version Addons20
01:07:16 T:18446744072347124480  NOTICE:  Running database version ViewModes6
01:07:16 T:18446744072347124480  NOTICE:  Running database version Textures13
01:07:16 T:18446744072347124480  NOTICE:  Running database version MyMusic56
01:07:16 T:18446744072347124480  NOTICE:  Running database version MyVideos99
01:07:16 T:18446744072347124480  NOTICE:  Running database version TV29
01:07:16 T:18446744072347124480  NOTICE:  Running database version Epg11
01:07:17 T:18446744072347124480 WARNING:  JSONRPC: Could not parse type "Setting.Details.SettingList"
01:07:17 T:18446744072347124480  NOTICE:  ActiveAE DSP - starting
01:07:17 T:18446744072347124480  NOTICE:  initialize done
01:07:17 T:18446744072347124480  NOTICE:  Running the application...
01:07:17 T:18446744072347124480  NOTICE:  starting zeroconf publishing
01:07:17 T:18446744072347124480  NOTICE:  starting upnp client
01:07:17 T:18446744072347124480  NOTICE:  Current resolution: 1920x1080 @ 60.00 - Full Screen
01:07:17 T:18446744072347124480  NOTICE:  GL_VENDOR = ARM
01:07:17 T:18446744072347124480  NOTICE:  GL_RENDERER = Mali-450 MP
01:07:17 T:18446744072347124480  NOTICE:  GL_VERSION = OpenGL ES 2.0
01:07:17 T:18446744072347124480  NOTICE:  GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
01:07:17 T:18446744072347124480  NOTICE:  GL_EXTENSIONS = GL_EXT_debug_marker GL_OES_texture_npot GL_OES_vertex_array_object GL_OES_compressed_ETC1_RGB8_texture GL_EXT_compressed_ETC1_RGB8_sub_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_mapbuffer
01:07:17 T:18446744072043105152  NOTICE:  ES: Starting UDP Event server on 0.0.0.0:9777
01:07:17 T:18446744072043105152  NOTICE:  UDP: Listening on port 9777
01:07:19 T:18446744072092095744  NOTICE:  [script.module.magnetic]
01:07:19 T:18446744072092095744  NOTICE:  [script.module.magnetic]                           _   _
01:07:19 T:18446744072092095744  NOTICE:  [script.module.magnetic]  _ __  __ _ __ _ _ _  ___| |_(_)__
01:07:19 T:18446744072092095744  NOTICE:  [script.module.magnetic] | '  \/ _' / _' | ' \/ -_)  _| / _|
01:07:19 T:18446744072092095744  NOTICE:  [script.module.magnetic] |_|_|_\__,_\__, |_||_\___|\__|_\__|
01:07:19 T:18446744072092095744  NOTICE:  [script.module.magnetic]           |___/
01:07:19 T:18446744072092095744  NOTICE:  [script.module.magnetic]
01:07:19 T:18446744072092095744  NOTICE:  [script.module.magnetic] Author: mancuniancol
01:07:19 T:18446744072092095744  NOTICE:  [script.module.magnetic] Version: 0.9.55
01:07:19 T:18446744072092095744  NOTICE:  [script.module.magnetic] Magnetic service at 127.0.0.1:5005
01:07:39 T:18446744072043765760  NOTICE:  [plugin.video.quasar] quasar: starting jsonrpc service
01:07:39 T:18446744072043766400  NOTICE:  [plugin.video.quasar] quasard: starting quasard
01:07:39 T:18446744072043766400  NOTICE:  [plugin.video.quasar] Detected binary folder: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/bin/android_arm
01:07:39 T:18446744072043766400  NOTICE:  [plugin.video.quasar] Using binary folder: /storage/emulated/legacy/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/bin/android_arm
01:07:39 T:18446744072043766400  NOTICE:  [plugin.video.quasar] Updating quasar daemon...
01:07:40 T:18446744072043766400  NOTICE:  [plugin.video.quasar] Deleting stale files set([])
01:07:40 T:18446744072043766400   ERROR:  [plugin.video.quasar] Traceback (most recent call last):
01:07:40 T:18446744072043766400   ERROR:  [plugin.video.quasar]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 157, in quasard_thread
01:07:40 T:18446744072043766400   ERROR:  [plugin.video.quasar]     proc = start_quasard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
01:07:40 T:18446744072043766400   ERROR:  [plugin.video.quasar]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 135, in start_quasard
01:07:40 T:18446744072043766400   ERROR:  [plugin.video.quasar]     return subprocess.Popen(args, **kwargs)
01:07:40 T:18446744072043766400   ERROR:  [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/subprocess.py", line 633, in __init__
01:07:40 T:18446744072043766400   ERROR:  [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/subprocess.py", line 1139, in _execute_child
01:07:40 T:18446744072043766400   ERROR:  [plugin.video.quasar] OSError: [Errno 13] Permission denied
01:07:40 T:18446744072043766400   ERROR:  [plugin.video.quasar]
01:07:40 T:18446744072043766400   ERROR:  Exception in thread Thread-2:
                                           Traceback (most recent call last):
                                             File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/threading.py", line 532, in __bootstrap_inner
                                             File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/threading.py", line 484, in run
                                             File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 157, in quasard_thread
                                               proc = start_quasard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                             File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 135, in start_quasard
                                               return subprocess.Popen(args, **kwargs)
                                             File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/subprocess.py", line 633, in __init__
                                             File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/subprocess.py", line 1139, in _execute_child
                                           OSError: [Errno 13] Permission denied
01:07:52 T:18446744072350425216   ERROR:  EXCEPTION: Non-Existent Control 1
```

**Comment by pierrandre** [comment]
Bump,

I got the exact same issue with my Kodi 16.1 on the same matricom ARM android box.
I installed the last version of Quasar, but I get the same error message OSError: [Errno 13] Permission denied, and obviously nothing allow quasar to run.

OP posted his logfile all over the internet almost, and he got no answers, I don't know if he solved the issue.

Anyway, I'm bumping this bug because it is still impacting users.
thanks

**Comment by scakemyer** [comment]
Debug logs of the installation are needed if you want to get any kind of help, which is probably why this issue was left unanswered in the first place.

**Comment by dr1ss** [comment]
I'll retest this tonight and post the installation debug log, but since I reported this I've upgraded to Kodi 17 so I wonder if the problem persists...

**Comment by bloombergg** [comment]
after booting your matticom are there a series of toasts about chmod?

**Comment by pierrandre** [comment]
my error logs are exactly like above
the only prompt that I receive is the following with a Quasar icon:

OSError: [Errno 13] Permission denied
