### ISSUE TITLE
[Recovery] panic recovered

### ISSUE THREAD

**Issue by taymiri** [scakemyer/plugin.video.quasar#589]
Hello !
Since the two last update, i have a problem, i can't start videos. Kodi show the message "HttpError()"
And the log of kodi during launch a video is the following: 

```
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] Searching links for: 346672
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] Resolved 346672 to Underworld : Blood Wars
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar]
14:48:13 T:2219830080  NOTICE: Previous line repeats 1 times.
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] 2016/12/19 13:48:13 [Recovery] panic recovered:
14:48:13 T:2403302208   ERROR: [plugin.video.quasar] Traceback (most recent call last):
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]   File "/home/mediacenter/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 118, in run
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]     data = _json(url)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] GET /movie/346672/play HTTP/1.1
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]   File "/home/mediacenter/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 48, in _json
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]     return opener.open(url, data, timeout)
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 435, in open
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]     response = meth(req, response)
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]     'http', request, response, code, msg, hdrs)
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 473, in error
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]     return self._call_chain(*args)
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]     result = func(*args)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] Host: localhost:65251
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] Connection: close
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] Accept-Encoding: identity
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] Connection: close
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] User-Agent: Python-urllib/2.7
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar]
14:48:13 T:2219830080  NOTICE: Previous line repeats 1 times.
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] runtime error: invalid memory address or nil pointer dereference
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:458 (0x813268b)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:62 (0x8130f4b)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/sigpanic_unix.go:24 (0x814572a)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/xbmc/jsonrpc.go:45 (0x8255e7f)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/xbmc/addons.go:17 (0x8255705)
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
14:48:13 T:2403302208   ERROR: [plugin.video.quasar] HTTPError: HTTP Error 500: Internal Server Error
14:48:13 T:2403302208   ERROR: [plugin.video.quasar]
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/providers/xbmc.go:74 (0x838430c)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/providers/xbmc.go:84 (0x83845d0)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/movies.go:267 (0x821bc66)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/movies.go:345 (0x821cc89)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x833f009)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/recovery.go:45 (0x834cfba)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x833f009)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/logger.go:72 (0x834c43e)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x833f009)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:284 (0x8344693)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:265 (0x83443ba)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2022 (0x81b1263)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2202 (0x81b1b46)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:1579 (0x81af016)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/asm_386.s:1612 (0x815c641)
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] 
14:48:13 T:2219830080  NOTICE: [plugin.video.quasar] [GIN] 2016/12/19 - 13:48:13 | 500 |   13.492932ms | 127.0.0.1 |   GET     /movie/346672/play
14:48:13 T:2993449024   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.quasar/movie/346672/play]
```

We can see a 500 error message : "HTTPError: HTTP Error 500: Internal Server Error"
Same probleme after clear the cache.
And i think it's the same problem in configuration of the add-on in "Advenced->Update the library"
``
14:53:38 T:2219830080  NOTICE: [plugin.video.quasar] [GIN] 2016/12/19 - 13:53:38 | 200 |      54.181µs | 127.0.0.1 |   GET     /library/update
14:53:38 T:2202782528   ERROR: [plugin.video.quasar] Traceback (most recent call last):
14:53:38 T:2202782528   ERROR: [plugin.video.quasar]   File "/home/mediacenter/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 118, in run
14:53:38 T:2202782528   ERROR: [plugin.video.quasar]     data = _json(url)
14:53:38 T:2202782528   ERROR: [plugin.video.quasar]   File "/home/mediacenter/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 102, in _json
14:53:38 T:2202782528   ERROR: [plugin.video.quasar]     raise Exception(payload)
14:53:38 T:2202782528   ERROR: [plugin.video.quasar] Exception: DB path error
14:53:38 T:2202782528   ERROR: [plugin.video.quasar]
``

Thank's for your help : 
Config : 
- lubuntu 16.04 x86 kodi v17
- The both "remote control" enable
- no firewall or something

**Comment by taymiri** [comment]
I don't know why, bu after an hour of tried to repair, it work...
I deleted all files of Quasar and cloned the project throw github and update this add-on throw kodi, and it work... Not logical.

**Comment by scakemyer** [comment]
Quasar crashed when closing the RPC connection to Kodi here `xbmc/jsonrpc.go:45`... And when you tried to update the library: `Exception: DB path error`, so it was definitely something with your setup.
