### ISSUE TITLE
Choosing Trakt as TV scraper setting for Kodi content causes crash when content is not actually scraped from Trakt

### ISSUE THREAD

**Issue by lafayetteduarte** [scakemyer/plugin.video.quasar#673]
Hi,
My quasard  keeps restarting in a loop .
my system is running on a raspberry pi 3 and openElec, Kodi 16.1:

Quasar/v0.9.61

Can you help with this issue?

Here is the info:
```
12:12:20  11.944328 T:1963827200  NOTICE: -----------------------------------------------------------------------
12:12:20  11.944414 T:1963827200  NOTICE: Starting Kodi (16.1 Git:ce88c8c). Platform: Linux ARM 32-bit
12:12:20  11.944480 T:1963827200  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
12:12:20  11.944555 T:1963827200  NOTICE: Kodi compiled Jan 11 2017 by GCC 5.4.0 for Linux ARM 32-bit version 4.4.41 (263209)
12:12:20  11.944866 T:1963827200  NOTICE: Running on OpenELEC (official) - Version: 7.0.1, kernel: Linux ARM 32-bit version 4.4.41
12:12:20  11.944932 T:1963827200  NOTICE: FFmpeg version: 2.8.7
12:12:20  11.944991 T:1963827200  NOTICE: WARNING: unsupported ffmpeg version detected
12:12:20  11.945054 T:1963827200  NOTICE: Host CPU: ARMv7 Processor rev 4 (v7l), 4 cores available
12:12:20  11.945110 T:1963827200  NOTICE: ARM Features: Neon enabled

<!--- Bug reports without logs will likely be dismissed and closed -->

19:44:03 633.328247 T:1580200864  NOTICE: Previous line repeats 9 times.
19:44:03 633.328430 T:1580200864  NOTICE: [plugin.video.quasar] panic: runtime error: invalid memory address or nil pointer dereference
19:44:03 633.329346 T:1580200864  NOTICE: [plugin.video.quasar] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2168a8]
19:44:03 633.330139 T:1580200864  NOTICE: [plugin.video.quasar]
19:44:03 633.330872 T:1580200864  NOTICE: [plugin.video.quasar] goroutine 87 [running]:
19:44:03 633.331543 T:1580200864  NOTICE: [plugin.video.quasar] panic(0x99dd18, 0x1110c010)
19:44:03 633.332214 T:1580200864  NOTICE: [plugin.video.quasar] 	/usr/local/go/src/runtime/panic.go:500 +0x33c
19:44:03 633.333191 T:1580200864  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/api.isDuplicateEpisode(0x577, 0x0, 0x1, 0x0, 0x0)
19:44:03 633.334167 T:1580200864  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:218 +0x8a4
19:44:03 633.335022 T:1580200864  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/api.writeShowStrm(0x11312b60, 0x4, 0x0, 0x948aa0, 0x0, 0x0)
19:44:03 633.335693 T:1580200864  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:670 +0x9f0
19:44:03 633.336426 T:1580200864  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/api.doUpdateLibrary.func1(0x11272d80, 0x0, 0x0)
19:44:03 633.337463 T:1580200864  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:357 +0x2e4
19:44:03 633.338440 T:1580200864  NOTICE: [plugin.video.quasar] github.com/boltdb/bolt.(*DB).View(0x11355b00, 0xa6cefc, 0x0, 0x0)
19:44:03 633.339172 T:1580200864  NOTICE: [plugin.video.quasar] 	/go/src/github.com/boltdb/bolt/db.go:629 +0xb0
19:44:03 633.339844 T:1580200864  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/api.doUpdateLibrary(0x0, 0x0)
19:44:03 633.340698 T:1580200864  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:362 +0x5c
19:44:03 633.341431 T:1580200864  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/api.LibraryUpdate.func4(0x12c)
19:44:03 633.342163 T:1580200864  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:1053 +0x74
19:44:03 633.343140 T:1580200864  NOTICE: [plugin.video.quasar] created by github.com/scakemyer/quasar/api.LibraryUpdate
19:44:03 633.344116 T:1580200864  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:1057 +0x678
19:44:03 633.345581 T:1580200864  NOTICE: [plugin.video.quasar] System information: linux_armv7 4.4.41
19:44:03 633.346375 T:1580200864  NOTICE: [plugin.video.quasar] Kodi build version: 16.1 Git:ce88c8c
19:44:03 633.347168 T:1580200864  NOTICE: [plugin.video.quasar] OS type: Linux
19:44:03 633.348145 T:1580200864  NOTICE: [plugin.video.quasar] uname: ('Linux', 'OpenELEC', '4.4.41', '#1 SMP Wed Jan 11 15:08:33 CET 2017', 'armv7l', '')
19:44:06 636.350098 T:1580200864  NOTICE: [plugin.video.quasar] quasard: starting quasard
```

Thank you
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC):
* Operating System and version (Android 4/5/6, Windows 7/8/10, macOS 10.11, Ubuntu 16.10):
* Link to Kodi debug log:
<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

**Comment by scakemyer** [comment]
Looks like the Trakt TV scraper setting is causing this. I actually doubt you have Trakt IDs in your Kodi library, try choosing TVDB or TMDB in Quasar's settings; that setting must match the TV scraper you're using for your TV content in Kodi. I'll make sure there's no crash nonetheless in the next release but won't make a hotfix for this.

**Comment by lafayetteduarte** [comment]
Yep. 
Changed the setting to TVDB and its all good again.
Thanks a lot for your help @scakemyer !
