### ISSUE TITLE
Quasar crashes on startup (Kodi v17.0 - ver. 0.9.63)

### ISSUE THREAD

**Issue by Gugna** [scakemyer/plugin.video.quasar#692]
```
NOTICE: [plugin.video.quasar] DEBU  main         ▶ main             ________
NOTICE: [plugin.video.quasar] DEBU  main         ▶ main             \_____  \  __ _______    ___________ _______
NOTICE: [plugin.video.quasar] DEBU  main         ▶ main              /  / \  \|  |  \__  \  /  ___/\__  \\_  __ \
NOTICE: [plugin.video.quasar] DEBU  main         ▶ main             /   \_/.  \  |  // __ \_\___ \  / __ \|  | \/
NOTICE: [plugin.video.quasar] DEBU  main         ▶ main             \_____\ \_/____/(____  /____  >(____  /__|
NOTICE: [plugin.video.quasar] DEBU  main         ▶ main                    \__>          \/     \/      \/
NOTICE: [plugin.video.quasar] DEBU  main         ▶ main
NOTICE: [plugin.video.quasar] INFO  main         ▶ main             Version: v0.9.63 Go: go1.8rc3
NOTICE: [plugin.video.quasar] INFO  config       ▶ Reload           Reloading configuration...
NOTICE: [plugin.video.quasar] INFO  main         ▶ main             Addon: plugin.video.quasar v0.9.63
NOTICE: CVideoDatabase::CleanDatabase: Cleaning videodatabase done. Operation took 00:01
NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:11
NOTICE: [plugin.video.quasar] INFO  btservice    ▶ configure        Applying session settings...
NOTICE: [plugin.video.quasar] INFO  btservice    ▶ configure        UserAgent: Quasar/v0.9.63 libtorrent/1.1.1.0
NOTICE: [plugin.video.quasar] INFO  btservice    ▶ configure        Applying encryption settings...
NOTICE: [plugin.video.quasar] INFO  btservice    ▶ startServices    Starting LSD...
NOTICE: [plugin.video.quasar] INFO  btservice    ▶ startServices    Starting DHT...
NOTICE: [plugin.video.quasar] INFO  btservice    ▶ startServices    Starting UPNP...
NOTICE: [plugin.video.quasar] INFO  btservice    ▶ startServices    Starting NATPMP...
NOTICE: [plugin.video.quasar] INFO  tmdb         ▶ CheckApiKey      Checking TMDB API key...
NOTICE: [plugin.video.quasar] INFO  btservice    ▶ alertsConsumer   Consuming alerts...
NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        dht_bootstrap_alert: DHT bootstrap complete
NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        listen_succeeded_alert: successfully listening on [TCP] [::]:6881
NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        listen_succeeded_alert: successfully listening on [TCP] 0.0.0.0:6881
NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        listen_succeeded_alert: successfully listening on [UDP] 0.0.0.0:6881
NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        listen_succeeded_alert: successfully listening on [TCP] [::]:4849
NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        listen_succeeded_alert: successfully listening on [TCP] 0.0.0.0:4849
NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        listen_succeeded_alert: successfully listening on [TCP] [::]:4846
NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        listen_succeeded_alert: successfully listening on [TCP] 0.0.0.0:4846
NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        listen_succeeded_alert: successfully listening on [UDP] 0.0.0.0:4846
NOTICE: [plugin.video.quasar] NOTI  tmdb         ▶ CheckApiKey      TMDB API key check passed, using ae4bd1b...
NOTICE: [plugin.video.quasar] INFO  main         ▶ func6            Updating Kodi add-on repositories...
NOTICE: [plugin.video.quasar] Resetting RPC objects...
NOTICE: [plugin.video.quasar] NOTI  library      ▶ func3            Warming up caches...
NOTICE: [plugin.video.quasar] ERRO  xbmc         ▶ VideoLibraryGetMovies  invalid character 'H' looking for beginning of value
NOTICE: [plugin.video.quasar] ERRO  xbmc         ▶ VideoLibraryGetShows  invalid character 'H' looking for beginning of value
NOTICE: [plugin.video.quasar]
NOTICE: Previous line repeats 1 times.
NOTICE: [plugin.video.quasar] [31m2017/02/02 14:52:05 [Recovery] panic recovered:
NOTICE: [plugin.video.quasar] GET /notification?sender=xbmc&method=VideoLibrary.OnCleanFinished&data=bnVsbA== HTTP/1.1
NOTICE: [plugin.video.quasar] Host: localhost:65251
NOTICE: [plugin.video.quasar] Connection: close
NOTICE: [plugin.video.quasar] Accept-Encoding: identity
NOTICE: [plugin.video.quasar] Connection: close
NOTICE: [plugin.video.quasar] User-Agent: Python-urllib/2.7
NOTICE: [plugin.video.quasar]
NOTICE: Previous line repeats 1 times.
NOTICE: [plugin.video.quasar] runtime error: invalid memory address or nil pointer dereference
NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:489 (0x426a4a)
NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:63 (0x425bec)
NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/signal_windows.go:161 (0x438214)
NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/library.go:143 (0x868c43)
NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/library.go:1274 (0x86feb9)
NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x6ceeb7)
NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/logger.go:72 (0x6da146)
NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x6ceeb7)
NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/recovery.go:45 (0x6dac4a)
NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x6ceeb7)
NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:284 (0x6d3a8e)
NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:265 (0x6d3557)
NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2238 (0x5f46e0)
NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2568 (0x5f5620)
NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:1825 (0x5f22f8)
NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/asm_386.s:1629 (0x44b761)
NOTICE: [plugin.video.quasar] [0m
NOTICE: [plugin.video.quasar] ERRO  xbmc         ▶ VideoLibraryGetMovies  invalid character 'H' looking for beginning of value
NOTICE: [plugin.video.quasar] ERRO  xbmc         ▶ VideoLibraryGetShows  invalid character 'H' looking for beginning of value
NOTICE: [plugin.video.quasar]
NOTICE: Previous line repeats 1 times.
NOTICE: [plugin.video.quasar] [31m2017/02/02 14:52:05 [Recovery] panic recovered:
NOTICE: [plugin.video.quasar] GET /notification?sender=xbmc&method=VideoLibrary.OnScanFinished&data=bnVsbA== HTTP/1.1
NOTICE: [plugin.video.quasar] Host: localhost:65251
NOTICE: [plugin.video.quasar] Connection: close
NOTICE: [plugin.video.quasar] Accept-Encoding: identity
NOTICE: [plugin.video.quasar] Connection: close
NOTICE: [plugin.video.quasar] User-Agent: Python-urllib/2.7
NOTICE: [plugin.video.quasar]
NOTICE: Previous line repeats 1 times.
NOTICE: [plugin.video.quasar] runtime error: invalid memory address or nil pointer dereference
NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:489 (0x426a4a)
NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:63 (0x425bec)
NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/signal_windows.go:161 (0x438214)
NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/library.go:143 (0x868c43)
NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/library.go:1274 (0x86feb9)
NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x6ceeb7)
NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/logger.go:72 (0x6da146)
NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x6ceeb7)
NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/recovery.go:45 (0x6dac4a)
NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x6ceeb7)
NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:284 (0x6d3a8e)
NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:265 (0x6d3557)
NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2238 (0x5f46e0)
NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2568 (0x5f5620)
NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:1825 (0x5f22f8)
NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/asm_386.s:1629 (0x44b761)
NOTICE: [plugin.video.quasar] [0m
NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        external_ip_alert: external IP received: 77.49.147.111
NOTICE: [plugin.video.quasar] INFO  repository   ▶ fetchChangelog   Fetching add-on changelog for plugin.video.quasar...
NOTICE: [plugin.video.quasar] INFO  repository   ▶ fetchChangelog   Fetching add-on changelog for script.quasar.burst...
NOTICE: [plugin.video.quasar] INFO  repository   ▶ GetAddonsXMLChecksum  Last available release of plugin.video.quasar: v0.9.63
NOTICE: [plugin.video.quasar] INFO  repository   ▶ GetAddonsXMLChecksum  Last available release of script.quasar.burst: v0.3.4
NOTICE: [plugin.video.quasar] [GIN] 2017/02/02 - 14:52:08 | 200 [0m|     3.357192s | ::1 |  [0m GET     /repository/scakemyer/plugin.video.quasar/addons.xml.md5
NOTICE: [plugin.video.quasar] ERRO  xbmc         ▶ VideoLibraryGetMovies  invalid character 'H' looking for beginning of value
NOTICE: [plugin.video.quasar] ERRO  xbmc         ▶ VideoLibraryGetShows  invalid character 'H' looking for beginning of value
NOTICE: [plugin.video.quasar] panic: runtime error: invalid memory address or nil pointer dereference
NOTICE: [plugin.video.quasar] [signal 0xc0000005 code=0x0 addr=0x0 pc=0x868c43]
NOTICE: [plugin.video.quasar]
NOTICE: [plugin.video.quasar] goroutine 67 [running]:
NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/api.updateLibraryShows()
NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:143 +0x33
NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/api.LibraryUpdate.func2()
NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:987 +0x33
NOTICE: [plugin.video.quasar] created by github.com/scakemyer/quasar/api.LibraryUpdate
NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:988 +0x1d2
NOTICE: [plugin.video.quasar]
NOTICE: Previous line repeats 36 times.
NOTICE: [plugin.video.quasar] System information: windows_x86 7
NOTICE: [plugin.video.quasar] Kodi build version: 17.0 Git:20170201-a10c504
NOTICE: [plugin.video.quasar] OS type: Windows
NOTICE: [plugin.video.quasar] uname: ('Windows', 'Gugna-PC', '7', '6.1.7601', 'x86', 'x86 Family 6 Model 23 Stepping 6, GenuineIntel')
NOTICE: [plugin.video.quasar] quasard: starting quasard
NOTICE: [plugin.video.quasar] Deleting stale files set([])
ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
ERROR: CCurlFile::Open failed with code 0 for http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml
ERROR: CRepository: failed to read http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml
```

## Context
When Kodi starts it performs the regular scans and then the notification that Quasar daemon has started comes up. Then after a couple of seconds a notification shows up that Quasar has crashed and is restarting.

## Your Environment
Windows 7 x86, Kodi v17.0 but same happened with Kodi v16.1. Quasar v. 0.9.63 but the same happened with v. 0.9.61 and another earlier version that I didn't write down. I have forwarded the ports used by Quasar, the process is white-listed in my firewall and tried the solution of Uninstalling, rebooting, deleting plugin folder then re-installing but problem didn't go away.

**Comment by scakemyer** [comment]
Already fixed in scakemyer/quasar@ad840da for 0.9.64 later today, #673 and #679 might also help meanwhile.
