### ISSUE TITLE
Quasar 0.9.65 no access to sub categories

### ISSUE THREAD

**Issue by Marcobi81** [scakemyer/plugin.video.quasar#696]
Quasar 0.9.65

Hello,
Just after the update, any try to access sub-categories goes timeout.
Thank you form the support.

```
35 2168.291260 T:1760555936  NOTICE: [plugin.video.quasar] [GIN] 2017/02/03 - 21:40:35 | 200 [0m|     475.209µs | 127.0.0.1 |  [0m GET     /
21:40:38 2172.139160 T:1760555936  NOTICE: [plugin.video.quasar] [GIN] 2017/02/03 - 21:40:38 | 200 [0m|    6.811081ms | 127.0.0.1 |  [0m GET     /shows/
21:45:44 2477.813965 T:1550091168   ERROR: [plugin.video.quasar] Traceback (most recent call last):
21:45:44 2477.814697 T:1550091168   ERROR: [plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 130, in run
21:45:44 2477.815186 T:1550091168   ERROR: [plugin.video.quasar]     data = _json(url)
21:45:44 2477.815674 T:1550091168   ERROR: [plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 47, in _json
21:45:44 2477.816162 T:1550091168   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
21:45:44 2477.816650 T:1550091168   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.2/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 154, in urlopen
21:45:44 2477.817383 T:1550091168   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.2/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 431, in open
21:45:44 2477.817871 T:1550091168   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.2/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 449, in _open
21:45:44 2477.818359 T:1550091168   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.2/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
21:45:44 2477.818848 T:1550091168   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.2/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 1227, in http_open
21:45:44 2477.819092 T:1550091168   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.2/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 1200, in do_open
21:45:44 2477.819580 T:1550091168   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.2/Python-2.7.11/.install_pkg/usr/lib/python2.7/httplib.py", line 1136, in getresponse
21:45:44 2477.820068 T:1550091168   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.2/Python-2.7.11/.install_pkg/usr/lib/python2.7/httplib.py", line 453, in begin
21:45:44 2477.820557 T:1550091168   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.2/Python-2.7.11/.install_pkg/usr/lib/python2.7/httplib.py", line 409, in _read_status
21:45:44 2477.821045 T:1550091168   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.2/Python-2.7.11/.install_pkg/usr/lib/python2.7/socket.py", line 480, in readline
21:45:44 2477.821533 T:1550091168   ERROR: [plugin.video.quasar] timeout: timed out
21:45:44 2477.822021 T:1550091168   ERROR: [plugin.video.quasar]
21:45:44 2477.959717 T:1962991616   ERROR: GetDirectory - Error getting plugin://plugin.video.quasar/shows/popular
21:45:44 2477.962402 T:1962991616   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/shows/popular) failed
21:45:45 2478.407471 T:1760555936  NOTICE: [plugin.video.quasar] [GIN] 2017/02/03 - 21:45:45 | 200 [0m|    1.804027ms | 127.0.0.1 |  [0m GET     /shows/
```

**Comment by scakemyer** [comment]
Please try that again by filling the issue template properly, and providing full logs, I can't do anything with just this...

**Comment by thatguy93** [comment]
Same problem, seems like this addon never works properly

**Comment by MrLegendary** [comment]
Don't be such a disrespectful ***. Scakemyer and others work very hard (for free!) for this addon. 

This isn't netflix. Don't expect it to be.

**Comment by scakemyer** [comment]
@thatguy93 Then just don't use it and kindly go f*** yourself.

**Comment by bluenote73** [comment]
You can feel free to use something else and complain to them then thatguy.

**Comment by Marcobi81** [comment]
Hey don't flame on my thread! ;)
I run quasar on Kodi (16.1 Git:c327c53)  x32 build (version for Raspberry Pi) LibreELEC (official) - Version: 7.0.2, kernel: Linux ARM 32-bit version 4.4.13

The isssue is the following: just after update to 0.9.65 from .55 version, every try to access the TV shows and Movies sub categories goes timeout.
here attached the full log.

Anyway, quasar is a nice addon :)
[kodi.txt](https://github.com/scakemyer/plugin.video.quasar/files/752288/kodi.txt)

**Comment by scakemyer** [comment]
Caches haven't finished warming up... Are you clearing them between each try? Either way, just give it a few minutes after it started up then try again. I'll try to think of something so that cache warming doesn't block access to anything. It shouldn't in the first place anyway, but seems like it does for some reason.

**Comment by Marcobi81** [comment]
Everything is working fine just after a system reboot. Hope this issue could be useful anyway.
