### ISSUE TITLE
'Server Internal Error' when trying to navigate to sub-categories. 

### ISSUE THREAD

**Issue by kodi4you** [scakemyer/plugin.video.quasar#844]
## Context ## Steps to Reproduce (for bugs):
Steps:
1) Open the add-on
2) Go to TV shows category
3) Try to go to any other subcategory, I started with 'Popular'
Expected:
'Popular' category should be opened quickly.
Results:
Failed to navigate to this sub-category. Error message- see quasar error messate on the kodi Gui- 'Server Internal Error'.
In kodi.log, copied everything I found during this error:
02:32:53 46949.703125 T:1843393440  NOTICE: [plugin.video.quasar] GET /shows/popular HTTP/1.1
02:32:53 46949.703125 T:1843393440  NOTICE: [plugin.video.quasar] Host: localhost:65251
02:32:53 46949.703125 T:1843393440  NOTICE: [plugin.video.quasar] Connection: close
02:32:53 46949.703125 T:1843393440  NOTICE: [plugin.video.quasar] Accept-Encoding: identity
02:32:53 46949.707031 T:1843393440  NOTICE: [plugin.video.quasar] Connection: close
02:32:53 46949.707031 T:1063252896   ERROR: [plugin.video.quasar] Traceback (most recent call last):
02:32:53 46949.707031 T:1063252896   ERROR: [plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 178, in run
02:32:53 46949.707031 T:1063252896   ERROR: [plugin.video.quasar]     data = _json(url)
02:32:53 46949.707031 T:1063252896   ERROR: [plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 125, in _json
02:32:53 46949.707031 T:1063252896   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
02:32:53 46949.707031 T:1063252896   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.3/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 154, in urlopen
02:32:53 46949.707031 T:1063252896   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.3/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 437, in open
02:32:53 46949.710938 T:1063252896   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.3/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 550, in http_response
02:32:53 46949.710938 T:1063252896   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.3/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 475, in error
02:32:53 46949.710938 T:1063252896   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.3/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
02:32:53 46949.710938 T:1063252896   ERROR: [plugin.video.quasar]   File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.3/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
02:32:53 46949.710938 T:1063252896   ERROR: [plugin.video.quasar] HTTPError: HTTP Error 500: Internal Server Error
02:32:53 46949.710938 T:1063252896   ERROR: [plugin.video.quasar]
02:32:54 46950.007812 T:1963220992   ERROR: GetDirectory - Error getting plugin://plugin.video.quasar/shows/popular
02:32:54 46950.011719 T:1963220992   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/shows/popular) failed
02:32:54 46950.011719 T:1843393440  NOTICE: [plugin.video.quasar] User-Agent: Python-urllib/2.7
02:32:54 46950.011719 T:1843393440  NOTICE: [plugin.video.quasar]
02:32:54 46950.039062 T:1843393440  NOTICE: Previous line repeats 1 times.
02:32:54 46950.039062 T:1843393440  NOTICE: [plugin.video.quasar] runtime error: invalid memory address or nil pointer dereference
02:32:54 46950.042969 T:1843393440  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:489 (0x119f28)
02:32:54 46950.054688 T:1843393440  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:63 (0x118f38)
02:32:54 46950.054688 T:1843393440  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/signal_unix.go:290 (0x12e504)
02:32:54 46950.054688 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/boltdb/bolt/db.go:470 (0x323f5c)
02:32:54 46950.054688 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/boltdb/bolt/db.go:463 (0x323f20)
02:32:54 46950.074219 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/boltdb/bolt/db.go:613 (0x32483c)
02:32:54 46950.109375 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/library.go:349 (0x5a8d98)
02:32:54 46950.117188 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/shows.go:152 (0x5c297c)
02:32:54 46950.121094 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/shows.go:202 (0x5c30d4)
02:32:54 46950.121094 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x3ed984)
02:32:54 46950.128906 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/cache/cache.go:116 (0x4ddf98)
02:32:54 46950.128906 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x3ed984)
02:32:54 46950.128906 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/logger.go:72 (0x3f93a8)
02:32:54 46950.187500 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x3ed984)
02:32:54 46950.187500 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/recovery.go:45 (0x3f9e70)
02:32:54 46950.203125 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x3ed984)
02:32:54 46950.265625 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:284 (0x3f2744)
02:32:54 46950.265625 T:1843393440  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:265 (0x3f21f8)
02:32:54 46950.269531 T:1843393440  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2238 (0x2f97fc)
02:32:54 46950.269531 T:1843393440  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2568 (0x2fa7a8)
02:32:54 46950.269531 T:1843393440  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:1825 (0x2f735c)
02:32:54 46950.269531 T:1843393440  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/asm_arm.s:1017 (0x142be4)
02:32:54 46950.273438 T:1843393440  NOTICE: [plugin.video.quasar] 

## Your Environment
Raspberru Pi 3 , wired Internet connection (
* Version used:
0.9.78
* Environment name and version:
Kodi version 16 [Jarvis]  LibreELEC, 
* Operating System and version:
LibreELEC (official) Version: 7.0.3
 uname -a :
Linux LibreELEC 4.4.13 #1 SMP Sat Nov 26 09:36:16 GMT 2016 armv7l GNU/Linux

**Comment by elgatito** [comment]
Please, provide a kodi.log with debug enabled.
http://kodi.wiki/view/Log_file/Easy

Delete `library.db` file from Quasar directory in `userdata` and retry.

**Comment by philwolstenholme** [comment]
Deleting `library.db` worked for me

**Comment by manuchant** [comment]
Deleting library.db worked for me too

**Comment by marine1988** [comment]
not worked for me

**Comment by SrNetoChan** [comment]
I got this error, but restarting kodi fixed it.
