### ISSUE TITLE
ERROR: [plugin.video.quasar] Traceback (most recent call last):

### ISSUE THREAD

**Issue by thiago-prado-cavalcanti** [scakemyer/plugin.video.quasar#865]
When navigating to the fourth page in any Quasar section (Movies Most Popular, Top Rated, etc) I got an "Internal Server Error"

------------ FULL LOG --------------
https://paste.ubuntu.com/24798186/

------------ PARTIAL LOG --------------
00:44:39.281 T:140344645965568  NOTICE: [plugin.video.quasar] runtime error: slice bounds out of range
00:44:39.281 T:140344645965568  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:489 (0x5276cf)
00:44:39.281 T:140344645965568  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:35 (0x5263be)
00:44:39.282 T:140344645965568  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/movies.go:164 (0xac53f1)
00:44:39.282 T:140344645965568  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/movies.go:254 (0xac5591)
00:44:39.282 T:140342352578304   ERROR: [plugin.video.quasar] Traceback (most recent call last):
00:44:39.282 T:140342352578304   ERROR: [plugin.video.quasar]   File "/home/thiagoprado/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 178, in run
00:44:39.282 T:140342352578304   ERROR: [plugin.video.quasar]     data = _json(url)
00:44:39.282 T:140342352578304   ERROR: [plugin.video.quasar]   File "/home/thiagoprado/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 125, in _json
00:44:39.282 T:140342352578304   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
00:44:39.282 T:140342352578304   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
00:44:39.283 T:140342352578304   ERROR: [plugin.video.quasar]     return opener.open(url, data, timeout)
00:44:39.283 T:140342352578304   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 435, in open
00:44:39.283 T:140342352578304   ERROR: [plugin.video.quasar]     response = meth(req, response)
00:44:39.283 T:140342352578304   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
00:44:39.283 T:140342352578304   ERROR: [plugin.video.quasar]     'http', request, response, code, msg, hdrs)
00:44:39.283 T:140342352578304   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 473, in error
00:44:39.283 T:140342352578304   ERROR: [plugin.video.quasar]     return self._call_chain(*args)
00:44:39.283 T:140342352578304   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
00:44:39.283 T:140342352578304   ERROR: [plugin.video.quasar]     result = func(*args)
00:44:39.283 T:140342352578304   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
00:44:39.283 T:140342352578304   ERROR: [plugin.video.quasar]     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
00:44:39.283 T:140342352578304   ERROR: [plugin.video.quasar] HTTPError: HTTP Error 500: Internal Server Error
00:44:39.283 T:140342352578304   ERROR: [plugin.video.quasar]
00:44:39.283 T:140344645965568  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x899b9a)
00:44:39.283 T:140342352578304    INFO: CPythonInvoker(11, /home/thiagoprado/.kodi/addons/plugin.video.quasar/navigation.py): script successfully run
00:44:39.298 T:140345656904064   DEBUG: ------ Window Init (DialogNotification.xml) ------
00:44:39.305 T:140342352578304    INFO: Python script stopped
00:44:39.305 T:140342352578304   DEBUG: Thread LanguageInvoker 140342352578304 terminating
00:44:39.305 T:140344645965568  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/cache/cache.go:116 (0x9b6627)
00:44:39.305 T:140344645965568  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x899b9a)
00:44:39.305 T:140344645965568  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/logger.go:72 (0x8a819f)
00:44:39.305 T:140344645965568  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x899b9a)
00:44:39.305 T:140344645965568  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/recovery.go:45 (0x8a8eca)
00:44:39.305 T:140344645965568  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x899b9a)
00:44:39.305 T:140344645965568  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:284 (0x89fd30)
00:44:39.305 T:140344645965568  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:265 (0x89f64b)
00:44:39.305 T:140344645965568  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2238 (0x771f10)
00:44:39.305 T:140344645965568  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2568 (0x773332)
00:44:39.305 T:140344645965568  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:1825 (0x76f532)
00:44:39.305 T:140344645965568  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/asm_amd64.s:2197 (0x553811)
00:44:39.305 T:140344645965568  NOTICE: [plugin.video.quasar] [0m
00:44:39.305 T:140344645965568  NOTICE: [plugin.video.quasar] [33mWARN  library      ▶ isDuplicateEpisode  [0mNo external IDs found for S01E03 (66292)
00:44:39.314 T:140345656904064   ERROR: GetDirectory - Error getting plugin://plugin.video.quasar/movies/popular?page=4
00:44:39.314 T:140345656904064   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/movies/popular?page=4) failed
00:44:39.314 T:140345656904064   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.quasar/movies/popular?page=3)
00:44:39.314 T:140345656904064   DEBUG:   ParentPath = [plugin://plugin.video.quasar/movies/popular?page=2]
00:44:39.323 T:140345035712256   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.quasar] took 10 ms
00:44:39.324 T:140342799832832   DEBUG: StartScript - calling plugin Quasar('plugin://plugin.video.quasar/movies/popular','7','?page=3')
00:44:39.324 T:140342352578304   DEBUG: Thread LanguageInvoker start, auto delete: false
00:44:39.324 T:140342352578304    INFO: initializing python engine.
00:44:39.324 T:140342352578304   DEBUG: CPythonInvoker(12, /home/thiagoprado/.kodi/addons/plugin.video.quasar/navigation.py): start processing
00:44:39.352 T:140342352578304   DEBUG: -->Python Interpreter Initialized<--
00:44:39.352 T:140342352578304   DEBUG: CPythonInvoker(12, /home/thiagoprado/.kodi/addons/plugin.video.quasar/navigation.py): the source file to load is "/home/thiagoprado/.kodi/addons/plugin.video.quasar/navigation.py"
00:44:39.352 T:140342352578304   DEBUG: CPythonInvoker(12, /home/thiagoprado/.kodi/addons/plugin.video.quasar/navigation.py): setting the Python path to /home/thiagoprado/.kodi/addons/plugin.video.quasar:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat
00:44:39.352 T:140342352578304   DEBUG: CPythonInvoker(12, /home/thiagoprado/.kodi/addons/plugin.video.quasar/navigation.py): entering source directory /home/thiagoprado/.kodi/addons/plugin.video.quasar
00:44:39.352 T:140342352578304   DEBUG: CPythonInvoker(12, /home/thiagoprado/.kodi/addons/plugin.video.quasar/navigation.py): instantiating addon using automatically obtained id of "plugin.video.quasar" dependent on version 2.24.0 of the xbmc.python api
00:44:39.814 T:140345656904064   DEBUG: ------ Window Init (DialogBusy.xml) ------
00:44:39.908 T:140342352578304   DEBUG: [plugin.video.quasar] Requesting http://localhost:65251/movies/popular?page=3 from ['plugin://plugin.video.quasar/movies/popular', '7', '?page=3']
00:44:39.913 T:140344645965568  NOTICE: [plugin.video.quasar] [GIN] 2017/06/07 - 03:44:39 | 200 [0m|    4.488398ms | 127.0.0.1 |  [0m GET     /movies/popular
00:44:39.959 T:140342352578304    INFO: CPythonInvoker(12, /home/thiagoprado/.kodi/addons/plugin.video.quasar/navigation.py): script successfully run

**Comment by jpmartinussi** [comment]
Same issue here!!!
