### ISSUE TITLE
Can't start daemon when used non-ascii characters in user profile name

### ISSUE THREAD

**Issue by RuslansAlistek** [scakemyer/plugin.video.quasar#875]
Quasar do not started because it can't decode non-ascii characters from profile folder path, and raise UnicodeEncodeError exception. For example: in my windows user name used Cyrillic characters.

## Log snippet of crash
13:53:34.681 T:3896  NOTICE: [plugin.video.quasar] Updating quasar daemon...
13:53:34.722 T:3896  NOTICE: [plugin.video.quasar] Deleting stale files set([])
13:53:35.106 T:4080   ERROR: [plugin.video.quasar] Traceback (most recent call last):
13:53:35.106 T:4080   ERROR: [plugin.video.quasar]   File "C:\Users\������\AppData\Roaming\Kodi\addons\plugin.video.quasar\resources\site-packages\quasar\daemon.py", line 214, in quasard_thread
13:53:35.106 T:4080   ERROR: [plugin.video.quasar]     proc = start_quasard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
13:53:35.107 T:4080   ERROR: [plugin.video.quasar]   File "C:\Users\������\AppData\Roaming\Kodi\addons\plugin.video.quasar\resources\site-packages\quasar\daemon.py", line 192, in start_quasard
13:53:35.107 T:4080   ERROR: [plugin.video.quasar]     return subprocess.Popen(args, **kwargs)
13:53:35.107 T:4080   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\subprocess.py", line 710, in __init__
13:53:35.107 T:4080   ERROR: [plugin.video.quasar]     errread, errwrite)
13:53:35.107 T:4080   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\subprocess.py", line 958, in _execute_child
13:53:35.107 T:4080   ERROR: [plugin.video.quasar]     startupinfo)
13:53:35.107 T:4080   ERROR: [plugin.video.quasar] UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-14: ordinal not in range(128)

## Your Environment
Version used:

- Version used:
Quasar v0.9.78 - libtorrent 1.1.1.0
- Environment name and version:
Kodi 17.3
- Operating System and version:
Windows 7

**Comment by placidities** [comment]
create new user with expected latin characters
