### ISSUE TITLE
Quasar times out accessing Trakt collection

### ISSUE THREAD

**Issue by oblitum** [scakemyer/plugin.video.quasar#904]
I've used the plugin with success past week, and trakt worked, but just on first day of use, since then it's always timing out after a couple of minutes. This is the relevant log for when I try to list my collection:

```
ERROR: Control 55 in window 10025 has been asked to focus, but it can't                                                                         
ERROR: CAESinkALSA - snd_pcm_writei(-32) Broken pipe - trying to recover                                                                        
ERROR: [plugin.video.quasar] Traceback (most recent call last):                                                                                 
ERROR: [plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 178, in run  
ERROR: [plugin.video.quasar]     data = _json(url)                                                                                              
ERROR: [plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 125, in _json
ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:                                                                
ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen                                                       
ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 429, in open                                                          
ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 447, in _open                                                         
ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain                                                   
ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open                                                    
ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open                                                      
ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse                                                  
ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/httplib.py", line 438, in begin                                                         
ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/httplib.py", line 394, in _read_status                                                  
ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/socket.py", line 480, in readline                                                       
ERROR: [plugin.video.quasar] timeout: timed out                                                                                                 
ERROR: [plugin.video.quasar]                                                                                                                    
ERROR: GetDirectory - Error getting plugin://plugin.video.quasar/shows/trakt/collection                                                         
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/shows/trakt/collection) failed                                                
```

- Quasar 0.9.78
- Kodi 17.5 Git:5bd45ab
- LibreELEC 8.2.0 imx6.arm

**Comment by oblitum** [comment]
Additional log with debug messages when I click the Trakt TV shows Collection button:

- [quasar.1.log](https://gist.githubusercontent.com/oblitum/fe719e5087066dda2ccb9b6f4ae40bea/raw/7a5237e98c2a30370e4328fa9059f7066e3762ce/quasar.1.log)
- [quasar.2.log](https://gist.githubusercontent.com/oblitum/fe719e5087066dda2ccb9b6f4ae40bea/raw/7a5237e98c2a30370e4328fa9059f7066e3762ce/quasar.2.log)

On quasar.2.log there's "json: cannot unmarshal array into Go value of type trakt.Show".

**Comment by oblitum** [comment]
Additional log with debug messages when I click the Trakt TV shows Collection button:

https://gist.githubusercontent.com/oblitum/fe719e5087066dda2ccb9b6f4ae40bea/raw/bf895b42089437bb1d4c719dfbddce2568002809/gistfile1.txt

**Comment by oblitum** [comment]
Additional log with debug messages when I click the Trakt TV shows Collection button:

https://gist.githubusercontent.com/oblitum/fe719e5087066dda2ccb9b6f4ae40bea/raw/bf895b42089437bb1d4c719dfbddce2568002809/gistfile1.txt
