### ISSUE TITLE
Error on rpi3 using any function of quasar

### ISSUE THREAD

**Issue by ceso** [scakemyer/plugin.video.quasar#920]
After an update quasar stop working on my rpi3 (a loop saying the quasar binary wasn't found even if it exist), I applied the solution that is described here

https://github.com/scakemyer/plugin.video.quasar/issues/918

It starts but now the issue is another, when I do a search or just hit "Recent Episodes" inside the Tv Shows section (or whiever of the others functions), for example, Quasar fails saying internal error, the logs it writes are:

```15:37:12.271 T:1679815424  NOTICE: [plugin.video.quasar] 2018/01/21 18:37:12 [Recovery] panic recovered:
15:37:12.271 T:1679815424  NOTICE: [plugin.video.quasar] GET /movies/search HTTP/1.1
15:37:12.273 T:1679815424  NOTICE: [plugin.video.quasar] Host: localhost:65251
15:37:12.273 T:1679815424  NOTICE: [plugin.video.quasar] Connection: close
15:37:12.274 T:1679815424  NOTICE: [plugin.video.quasar] Accept-Encoding: identity
15:37:12.275 T:1679815424  NOTICE: [plugin.video.quasar] Connection: close
15:37:12.276 T:1679815424  NOTICE: [plugin.video.quasar] User-Agent: Python-urllib/2.7
15:37:12.276 T:1679815424  NOTICE: [plugin.video.quasar]
15:37:12.278 T:1679815424  NOTICE: Previous line repeats 1 times.
15:37:12.278 T:1679815424  NOTICE: [plugin.video.quasar] runtime error: invalid memory address or nil pointer dereference
15:37:12.279 T:1679815424  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:489 (0x119f28)
15:37:12.280 T:1905259264   ERROR: [plugin.video.quasar] Traceback (most recent call last):
15:37:12.281 T:1905259264   ERROR: [plugin.video.quasar]   File "/home/osmc/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 178, in run
15:37:12.281 T:1905259264   ERROR: [plugin.video.quasar]     data = _json(url)
15:37:12.281 T:1905259264   ERROR: [plugin.video.quasar]   File "/home/osmc/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 125, in _json
15:37:12.282 T:1905259264   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
15:37:12.282 T:1905259264   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
15:37:12.282 T:1905259264   ERROR: [plugin.video.quasar]     return opener.open(url, data, timeout)
15:37:12.283 T:1905259264   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 435, in open
15:37:12.283 T:1905259264   ERROR: [plugin.video.quasar]     response = meth(req, response)
15:37:12.284 T:1905259264   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
15:37:12.284 T:1905259264   ERROR: [plugin.video.quasar]     'http', request, response, code, msg, hdrs)
15:37:12.284 T:1905259264   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 473, in error
15:37:12.285 T:1905259264   ERROR: [plugin.video.quasar]     return self._call_chain(*args)
15:37:12.285 T:1905259264   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
15:37:12.285 T:1905259264   ERROR: [plugin.video.quasar]     result = func(*args)
15:37:12.286 T:1905259264   ERROR: [plugin.video.quasar]   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
15:37:12.286 T:1905259264   ERROR: [plugin.video.quasar]     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
15:37:12.287 T:1905259264   ERROR: [plugin.video.quasar] HTTPError: HTTP Error 500: Internal Server Error
15:37:12.287 T:1905259264   ERROR: [plugin.video.quasar]
15:37:12.393 T:1679815424  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:63 (0x118f38)
15:37:12.394 T:1679815424  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/signal_unix.go:290 (0x12e504)
15:37:12.395 T:1679815424  NOTICE: [plugin.video.quasar] /go/src/github.com/boltdb/bolt/db.go:470 (0x323f5c)
15:37:12.395 T:1679815424  NOTICE: [plugin.video.quasar] /go/src/github.com/boltdb/bolt/db.go:463 (0x323f20)
15:37:12.396 T:1679815424  NOTICE: [plugin.video.quasar] /go/src/github.com/boltdb/bolt/db.go:613 (0x32483c)
15:37:12.397 T:1679815424  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/library.go:349 (0x5a8d98)
15:37:12.397 T:1679815424  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/movies.go:194 (0x5b3f58)
15:37:12.398 T:1679815424  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/movies.go:309 (0x5b4e20)
15:37:12.399 T:1926076928   ERROR: GetDirectory - Error getting plugin://plugin.video.quasar/movies/search
15:37:12.399 T:1679815424  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x3ed984)
15:37:12.400 T:1679815424  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/logger.go:72 (0x3f93a8)
15:37:12.401 T:1926076928   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/movies/search) failed
15:37:12.403 T:1679815424  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x3ed984)
15:37:12.404 T:1679815424  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/recovery.go:45 (0x3f9e70)
15:37:12.404 T:1679815424  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x3ed984)
15:37:12.405 T:1679815424  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:284 (0x3f2744)
15:37:12.406 T:1679815424  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:265 (0x3f21f8)
15:37:12.406 T:1679815424  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2238 (0x2f97fc)
15:37:12.407 T:1679815424  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2568 (0x2fa7a8)
15:37:12.407 T:1679815424  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:1825 (0x2f735c)
15:37:12.408 T:1679815424  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/asm_arm.s:1017 (0x142be4)
15:37:12.409 T:1679815424  NOTICE: [plugin.video.quasar] 
```
This happened using:
plugin.video.quasar-0.9.78.linux_armv7
Kodi 17.6 running on OSMC (4.9.29-13-osmc)
HW: Raspberry Pi 3

**Comment by lcassisi** [comment]
Same problem here. Fixed the problema installing and keeping this release: plugin.video.quasar-0.9.55.linux_armv7.zip
