### ISSUE TITLE
Stuck on opening stream since 0.9.7/8

### ISSUE THREAD

**Issue by fabrizio5680** [scakemyer/plugin.video.quasar#94]
Quasar seems to hang at opening streams and not call on providers since 9.7. It will stay stuck on opening stream for as long as i let it or until i cancel to which it will respond fine but never open or return stream. Choose Stream has same behaviour. Attached debug logs. I have tried completely uninstalling plug and all providers.

Android arm7

[debug.txt](https://github.com/scakemyer/plugin.video.quasar/files/120508/debug.txt)

**Comment by fabrizio5680** [comment]
Not sure if related.. I've tried several things, still can't get it to work. Works very well on mac on the same network. Might no be related to latest version. Something to do with  URLError: <urlopen error timed out>

```
00:03:24 T:1987210856   ERROR: Exception
00:03:24 T:1987210856   ERROR: SystemExit
00:03:24 T:1987210856   ERROR:  in
00:03:24 T:1987210856   ERROR: <bound method _fileobject.__del__ of <socket._fileobject object at 0x703688a0>>
00:03:24 T:1987210856   ERROR:  ignored
00:03:24 T:1987210856   ERROR: [plugin.video.quasar] Traceback (most recent call last):
00:03:24 T:1987210856   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 96, in run
00:03:24 T:1987210856   ERROR: [plugin.video.quasar]     data = _json(url)
00:03:24 T:1987210856   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 48, in _json
00:03:24 T:1987210856   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
00:03:24 T:1987210856   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 126, in urlopen
00:03:24 T:1987210856   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 391, in open
00:03:24 T:1987210856   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 409, in _open
00:03:24 T:1987210856   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 369, in _call_chain
00:03:24 T:1987210856   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 1161, in http_open
00:03:24 T:1987210856   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 1136, in do_open
00:03:24 T:1987210856   ERROR: [plugin.video.quasar] URLError: <urlopen error timed out>
00:03:24 T:1987210856   ERROR: [plugin.video.quasar]
00:03:24 T:1987210856   DEBUG: POParser: loaded 60 strings from file /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/language/English/strings.po
00:03:24 T:1987210856    INFO: CPythonInvoker(38, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/navigation.py): script successfully run

```

**Comment by fabrizio5680** [comment]
Could be related to Remote communication server failing to start..

**Comment by fabrizio5680** [comment]
found culprit finally after much digging. Had installed an app on Android called Autostart & Stay, which the remote part shares 9090 port and therefore was blocking kodi *facepalm*

Closing issue.
